force-app/main/default/objects/Account_Relationship__c/Account_Relationship__c.object-meta.xml
<CustomObject>
    <label>Organization Relationship</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Account Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organization Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Relationship__c/fields/From_Account__c.field-meta.xml
<CustomField>
    <fullName>From_Account__c</fullName>
    <businessOwnerGroup>Customer_Master_Owners</businessOwnerGroup>
    <complianceGroup>None</complianceGroup>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field stores parent Account details for HCO-HCO relationship</description>
    <inlineHelpText>This field stores parent Account details for HCO-HCO relationship</inlineHelpText>
    <label>From Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Relationships</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Relationship__c/fields/Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Type__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>This field stores type of HCO-HCO relationship</description>
    <inlineHelpText>This field stores type of HCO-HCO relationship</inlineHelpText>
    <label>Relationship Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Managed</fullName>
            </value>
            <value>
                <fullName>ShipTo</fullName>
            </value>
            <value>
                <fullName>SoldTo</fullName>
            </value>
            <value>
                <fullName>BillTo</fullName>
            </value>
            <value>
                <fullName>Payer</fullName>
            </value>
            <value>
                <fullName>GroupPurchasingService</fullName>
            </value>
            <value>
                <fullName>DentalCareService</fullName>
            </value>
            <value>
                <fullName>TreatmentPlanningService</fullName>
            </value>
            <value>
                <fullName>ProductionService</fullName>
            </value>
            <value>
                <fullName>MentoringService</fullName>
            </value>
            <value>
                <fullName>ImagingService</fullName>
            </value>
            <value>
                <fullName>FinancingService</fullName>
            </value>
            <value>
                <fullName>AccountingService</fullName>
            </value>
            <value>
                <fullName>Leasing_RentalService</fullName>
            </value>
            <value>
                <fullName>InsuranceService</fullName>
            </value>
            <value>
                <fullName>Parent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Relationship__c/fields/To_Account__c.field-meta.xml
<CustomField>
    <fullName>To_Account__c</fullName>
    <businessOwnerGroup>Customer_Master_Owners</businessOwnerGroup>
    <complianceGroup>None</complianceGroup>
    <description>This field stores child Account for HCO-HCO relationship</description>
    <inlineHelpText>This field stores child Account for HCO-HCO relationship</inlineHelpText>
    <label>To Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Relationships1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountContactRelation/fields/Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Type__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>This field stores relationship type for HCO-HCP relationship</description>
    <inlineHelpText>This field stores relationship type for HCO-HCP relationship</inlineHelpText>
    <label>Relationship Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>Member</fullName>
            </value>
            <value>
                <fullName>IndependentContractor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Master_Enterprise_Payload__e/Customer_Master_Enterprise_Payload__e.object-meta.xml
<CustomObject>
    <description>Customer Master Enterprise Payload</description>
    <label>Customer Master Enterprise Payload</label>
    <pluralLabel>Customer Master Enterprise Payload</pluralLabel>
</CustomObject>

force-app/main/default/objects/Customer_Master_Enterprise_Payload__e/fields/Input_Json__c.field-meta.xml
<CustomField>
    <fullName>Input_Json__c</fullName>
    <complianceGroup>PII</complianceGroup>
    <description>Input Json</description>
    <label>Input Json</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Customer_Master_Enterprise_Payload__e/fields/Process__c.field-meta.xml
<CustomField>
    <fullName>Process__c</fullName>
    <complianceGroup>HIPAA</complianceGroup>
    <description>Process</description>
    <label>Process</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CM_EnterprisePayloadTriggerHelper.cls
/***********************************************************************************************************************
 * Name: CM_EnterprisePayloadTriggerHelper
 * Copyright © Align Tech
 * ========================================================================================================================
 * Purpose: Helper for CM_EnterprisePayloadTriggerHandler
 * TestClass : CM_EnterprisePayloadTriggerHelper
 * ========================================================================================================================
 * History
 *
 * VERSION         AUTHOR                          DATE                DETAIL
 * 1.0             Sruthi M                   08/01/2024             Helper for CRM Enterprise events
 ***********************************************************************************************************************/
public with sharing class CM_EnterprisePayloadTriggerHelper {
    /**********Metadat Records.************ */
    final Static Map <String, CM_ReltioHandlerService.SobjectData > accountRelation = CM_ReltioHandlerService.metadataRecords(CM_ReltioConstants.ACCRELALIONSERV);
    /**********Metadat Records.************ */
    final Static Map <String, CM_ReltioHandlerService.SobjectData > accConRelation = CM_ReltioHandlerService.metadataRecords(CM_ReltioConstants.ACCCONRELALIONS);
    /**      
     * @description : Method to handle enterprise payload event data
     */
    public static void reltioPayloadTriggerService(List < Customer_Master_Enterprise_Payload__e > masterRecord) {       
        final List<Account_Relationship__c> accountRelations = new List<Account_Relationship__c>();
        final List<AccountContactRelation> accConRelations = new List<AccountContactRelation>();
        for (Customer_Master_Enterprise_Payload__e event: masterRecord) {
            if (event.Process__c == CM_ReltioConstants.ACCRELALIONSERV) {
                accountRelations.add((Account_Relationship__c) System.JSON.deserialize(event.Input_Json__c, Account_Relationship__c.class)); 
            }
            if (event.Process__c == CM_ReltioConstants.ACCCONRELALIONS) {
                accConRelations.add((AccountContactRelation) System.JSON.deserialize(event.Input_Json__c, AccountContactRelation.class));
            }
        }        
        if(accountRelations!=null && !accountRelations.isEmpty()) {
            accountRelations(accountRelations);
        }        
        if(accConRelations!=null && !accConRelations.isEmpty()) {
            accountContactRelations(accConRelations);
        }
        UCB_LoggerService.publishLogs(); 
    }
    /**      
     * @description : Method to handle Account-Account relation data
     */
    private static void accountRelations(List<Account_Relationship__c> accountRelations) {
        final Map < String, Map < String, Sobject >> upsertMap = new Map < String, Map < String, Sobject >> ();
        Map < String, Account > accountMap = new Map < String, Account >();
        for(Account_Relationship__c relationship : accountRelations ) {
            accountMap = upsertAccountRelation(relationship,accountMap);
        }
        upsertMap.put('Account',accountMap);
        CM_DMLSaveResult.upsertRecords(upsertMap, accountRelation, CM_ReltioConstants.ACCRELALIONSERV);
    }
    private static Map < String, Account > upsertAccountRelation(Account_Relationship__c relationship,Map < String, Account > accountMap) {
        final Account account = new Account();
        account.Id = relationship.To_Account__c;
        account.ParentId = relationship.From_Account__c;
        accountMap.put(account.Id, account);
        return accountMap;
    }
    private static void accountContactRelations(List<AccountContactRelation> accConRelations) {
        final Map < String, Map < String, Sobject >> upsertMap = new Map < String, Map < String, Sobject >> ();
        final List<Id> conIdLists = new List<Id>();
        final List<Id> accIds = new List<Id>();
        final Map < String, Sobject > contactmap = new Map < String, Sobject > ();
        final Map < String, List<Id> > accMap = new Map < String, List<Id> >();
        final List<Contact> contUpdtLst;
        for(AccountContactRelation relation : accConRelations) {
            //conIdLists.add(relation.contactId);
            accIds.add(relation.AccountId);
        }
        if(!accIds.isEmpty() && accIds.size()!=null) {
        	accMap.put('Associate ContAcct',accIds);    
        }
        
        /* String lastRelAccount;
        String lastRelOwnerAccount;
         for(Contact con : [Select Id,
            (Select accountId,Relationship_Type__c from AccountContactRelations  order by startdate asc)
            from Contact where Id = :conIdLists  WITH SECURITY_ENFORCED ]) {
            system.debug('@rohit1@'+con);
            lastRelAccount=null;
            lastRelOwnerAccount= null;
            Contact cont = new Contact();
            cont.Id = con.Id;
            cont.accountId = null;
            for(AccountContactRelation relation : con.AccountContactRelations){
                if(String.isempty(lastRelAccount)){
                    lastRelAccount=relation.accountId;    
                }
                if(relation.Relationship_Type__c=='Owner' && String.isEmpty(lastRelOwnerAccount)) { 
                    lastRelOwnerAccount=relation.accountId;  
                }
            }
            cont.accountId = String.isempty(lastRelAccount)?lastRelAccount:lastRelAccount;
            contactmap.put(con.Id,cont);
        } */
        contUpdtLst = CM_AccountInactiveService.getContwithActiveAccnt(accMap);
        for(Contact cont : contUpdtLst) {
        	contactmap.put(cont.Id,cont);    
        }
        upsertMap.put('Contact',contactmap);
        CM_DMLSaveResult.upsertRecords(upsertMap, accConRelation, CM_ReltioConstants.ACCCONRELALIONS);
    }
    private CM_EnterprisePayloadTriggerHelper() {}
}