force-app/main/default/objects/Account_Relationship__c/Account_Relationship__c.object-meta.xml
<CustomObject>
    <label>Organization Relationship</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Account Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organization Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Relationship__c/fields/From_Account__c.field-meta.xml
<CustomField>
    <fullName>From_Account__c</fullName>
    <businessOwnerGroup>Customer_Master_Owners</businessOwnerGroup>
    <complianceGroup>None</complianceGroup>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field stores parent Account details for HCO-HCO relationship</description>
    <inlineHelpText>This field stores parent Account details for HCO-HCO relationship</inlineHelpText>
    <label>From Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Relationships</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Relationship__c/fields/Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Type__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>This field stores type of HCO-HCO relationship</description>
    <inlineHelpText>This field stores type of HCO-HCO relationship</inlineHelpText>
    <label>Relationship Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Managed</fullName>
            </value>
            <value>
                <fullName>ShipTo</fullName>
            </value>
            <value>
                <fullName>SoldTo</fullName>
            </value>
            <value>
                <fullName>BillTo</fullName>
            </value>
            <value>
                <fullName>Payer</fullName>
            </value>
            <value>
                <fullName>GroupPurchasingService</fullName>
            </value>
            <value>
                <fullName>DentalCareService</fullName>
            </value>
            <value>
                <fullName>TreatmentPlanningService</fullName>
            </value>
            <value>
                <fullName>ProductionService</fullName>
            </value>
            <value>
                <fullName>MentoringService</fullName>
            </value>
            <value>
                <fullName>ImagingService</fullName>
            </value>
            <value>
                <fullName>FinancingService</fullName>
            </value>
            <value>
                <fullName>AccountingService</fullName>
            </value>
            <value>
                <fullName>Leasing_RentalService</fullName>
            </value>
            <value>
                <fullName>InsuranceService</fullName>
            </value>
            <value>
                <fullName>Parent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Relationship__c/fields/To_Account__c.field-meta.xml
<CustomField>
    <fullName>To_Account__c</fullName>
    <businessOwnerGroup>Customer_Master_Owners</businessOwnerGroup>
    <complianceGroup>None</complianceGroup>
    <description>This field stores child Account for HCO-HCO relationship</description>
    <inlineHelpText>This field stores child Account for HCO-HCO relationship</inlineHelpText>
    <label>To Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Relationships1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Customer_Master_Enterprise_Payload__e/Customer_Master_Enterprise_Payload__e.object-meta.xml
<CustomObject>
    <description>Customer Master Enterprise Payload</description>
    <label>Customer Master Enterprise Payload</label>
    <pluralLabel>Customer Master Enterprise Payload</pluralLabel>
</CustomObject>

force-app/main/default/objects/Customer_Master_Enterprise_Payload__e/fields/Input_Json__c.field-meta.xml
<CustomField>
    <fullName>Input_Json__c</fullName>
    <complianceGroup>PII</complianceGroup>
    <description>Input Json</description>
    <label>Input Json</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Customer_Master_Enterprise_Payload__e/fields/Process__c.field-meta.xml
<CustomField>
    <fullName>Process__c</fullName>
    <complianceGroup>HIPAA</complianceGroup>
    <description>Process</description>
    <label>Process</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CM_AccountRelationshipTriggerHelper.cls
/***********************************************************************************************************************
 * Name: CM_AccountRelationshipTriggerHelper
 * Copyright © Align Tech
 * ========================================================================================================================
 * Purpose: Helper class for CM_AccountRelationshipTriggerHandler
 * TestClass : CM_AccountRelationshipTriggerHelper
 * ========================================================================================================================
 * History
 *
 * VERSION         AUTHOR                          DATE                DETAIL
 * 1.0             Sruthi M                  08/01/2024          Trigger helper publishes event for Account-Account Relationship
 ***********************************************************************************************************************/
public with sharing class CM_AccountRelationshipTriggerHelper {
    /**     
     * @description : publish the PE for the Account relationship record
     */
    public static void publishEvent(List < Account_Relationship__c > relationshipList) {
        final List < Customer_Master_Enterprise_Payload__e > payloadList = new List < Customer_Master_Enterprise_Payload__e > ();
        Customer_Master_Enterprise_Payload__e record;
        for (Account_Relationship__c relationship: relationshipList) {
            if(relationship.Relationship_Type__c == CM_ReltioConstants.ISAFFILIATED && 
                relationship.From_Account__c!=relationship.To_Account__c) {
                record = new Customer_Master_Enterprise_Payload__e();
                record.Input_Json__c = json.serialize(relationship);
                record.Process__c = CM_ReltioConstants.ACCRELALIONSERV;
                payloadList.add(record);
            }
        }
        if(payloadList!=null && !payloadList.isEmpty()) {
            eventbus.publish(payloadList);
        }        
    }
    private CM_AccountRelationshipTriggerHelper() {} 
}