force-app/main/default/objects/Account_Relationship__c/Account_Relationship__c.object-meta.xml
<CustomObject>
    <label>Organization Relationship</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Account Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organization Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Relationship__c/fields/From_Account__c.field-meta.xml
<CustomField>
    <fullName>From_Account__c</fullName>
    <businessOwnerGroup>Customer_Master_Owners</businessOwnerGroup>
    <complianceGroup>None</complianceGroup>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field stores parent Account details for HCO-HCO relationship</description>
    <inlineHelpText>This field stores parent Account details for HCO-HCO relationship</inlineHelpText>
    <label>From Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Relationships</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Master_Configurations__c/Customer_Master_Configurations__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Customer Master Configurations</description>
    <label>Customer Master Configurations</label>
</CustomObject>

force-app/main/default/objects/Exception_Handling__c/Exception_Handling__c.object-meta.xml
<CustomObject>
    <label>Exception Handling</label>
    <nameField>
        <displayFormat>Exception-{0000000}</displayFormat>
        <label>Exception Handling Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exception Handlings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Exception_Handling__c/fields/Process_Name__c.field-meta.xml
<CustomField>
    <fullName>Process_Name__c</fullName>
    <label>Process Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exception_Handling__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <description>For storing input in a json format</description>
    <label>Request</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Organization_Communication__c/Organization_Communication__c.object-meta.xml
<CustomObject>
    <label>Organization Communication</label>
    <nameField>
        <displayFormat>O-{000000}</displayFormat>
        <label>Organization Communication Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organization Communications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Organization_Communication__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>Master-details relationship to Account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Organization Communications</relationshipLabel>
    <relationshipName>Organization_Communications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Organization_E_Invoice__c/Organization_E_Invoice__c.object-meta.xml
<CustomObject>
    <label>Organization E-Invoice</label>
    <nameField>
        <displayFormat>OE-{000000}</displayFormat>
        <label>Organization E-Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organization E-Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Organization_E_Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>This is a Master-Detail relationship to Organization</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Organization E-Invoices</relationshipLabel>
    <relationshipName>Organization_E_Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reltio_CM_HCO_HCO_Inbound_Payload__e/Reltio_CM_HCO_HCO_Inbound_Payload__e.object-meta.xml
<CustomObject>
    <description>Reltio Customer Master HCO-HCO Inbound Payload</description>
    <label>Reltio CM HCO_HCO Inbound Payload</label>
    <pluralLabel>Reltio CM HCO_HCO Inbound Payload</pluralLabel>
</CustomObject>

force-app/main/default/classes/CM_ReltioHCOHCOPayloadTrigger_Test.cls
/***********************************************************************************************************************
* Name: CM_ReltioHCOHCOPayloadTrigger_Test
* Copyright © Align Tech
* ========================================================================================================================
* Purpose: Subscriber of Reltio  MDM platform event
* TestClass : CM_ReltioHCOHCOPayloadTrigger_Test
* ========================================================================================================================
* History
*
* VERSION         AUTHOR                          DATE                DETAIL
* 1.0             Rohit Jaiswal                   20/10/2023         Test class for Reltio HCOHCO trigger handler.
***********************************************************************************************************************/
@isTest
public with sharing class CM_ReltioHCOHCOPayloadTrigger_Test {

    @testSetup static void setupCustomSettingsData() {        
        Test.loadData(Customer_Master_Configurations__c.sObjectType, 'CustomerMasterConfigurations');
        Test.loadData(Exception_Handling__c.sObjectType, 'ReltioHCOHCORequests');   
    }
    @isTest 
    static void reltioHCOHCOService() {
        final List<Reltio_CM_HCO_HCO_Inbound_Payload__e> payloads = new List<Reltio_CM_HCO_HCO_Inbound_Payload__e>();
        final List<Account> acclist = new List<Account>();
        final List<Organization_E_Invoice__c> invoices = new List<Organization_E_Invoice__c>();
        final List<Organization_Communication__c> comminications = new List<Organization_Communication__c>();
        final List<Account_Relationship__c> relationShips = new List<Account_Relationship__c>();
        Test.startTest();  
        final Exception_Handling__c dataFacatory = [Select Request__c from Exception_Handling__c where Process_Name__c='HCOHCO1' limit 1];
        final Reltio_CM_HCO_HCO_Inbound_Payload__e payload = (Reltio_CM_HCO_HCO_Inbound_Payload__e) System.JSON.deserialize(dataFacatory.Request__c, Reltio_CM_HCO_HCO_Inbound_Payload__e.class);
        payloads.add(payload);
        EventBus.publish(payloads);
        Test.getEventBus().deliver();
        Test.stopTest();
        for(Account acc : [Select Id,(Select Id from Organization_Communications__r),(Select Id from Organization_E_Invoices__r),
                    (Select Id from Account_Relationships__r) from Account limit 4]) {
            acclist.add(acc);
            invoices.addall(acc.Organization_E_Invoices__r);
            comminications.addAll(acc.Organization_Communications__r);
            relationShips.addAll(acc.Account_Relationships__r);
        }
        System.assertEquals(acclist.size(),2,'Account Created');
        System.assertEquals(relationShips.size(),1,'Relationship Created');
    }
    @isTest 
    static void bulkHCOHCOService() {
        final  List<Reltio_CM_HCO_HCO_Inbound_Payload__e> payloads = new List<Reltio_CM_HCO_HCO_Inbound_Payload__e>();
        final List<Account> acclist = new List<Account>();
        final List<Organization_E_Invoice__c> invoices = new List<Organization_E_Invoice__c>();
        final List<Organization_Communication__c> comminications = new List<Organization_Communication__c>();
        final List<Account_Relationship__c> relationShips = new List<Account_Relationship__c>();
        Reltio_CM_HCO_HCO_Inbound_Payload__e payload;
        Test.startTest();
        for(Exception_Handling__c dataFacatory : [Select Request__c from Exception_Handling__c Limit 50] ) {
            payload = (Reltio_CM_HCO_HCO_Inbound_Payload__e) System.JSON.deserialize(dataFacatory.Request__c, Reltio_CM_HCO_HCO_Inbound_Payload__e.class);
            payloads.add(payload);
        }
        EventBus.publish(payloads);
        Test.getEventBus().deliver(); 
        Test.stopTest();
        for(Account acc : [Select Id,(Select Id from Organization_Communications__r),(Select Id from Organization_E_Invoices__r),
            (Select Id from Account_Relationships__r) from Account limit 1500]) {
            acclist.add(acc);
            invoices.addall(acc.Organization_E_Invoices__r);
            comminications.addAll(acc.Organization_Communications__r);
            relationShips.addAll(acc.Account_Relationships__r);
        }
        System.assertEquals(acclist.size(),100,'Account Created');
        System.assertEquals(relationShips.size(),50,'Relationship Created');
    }
    @isTest 
    static void replayService() {
        final  List<Reltio_CM_HCO_HCO_Inbound_Payload__e> payloads = new List<Reltio_CM_HCO_HCO_Inbound_Payload__e>();
        final List<Account> acclist = new List<Account>();
        final List<Organization_E_Invoice__c> invoices = new List<Organization_E_Invoice__c>();
        final List<Organization_Communication__c> comminications = new List<Organization_Communication__c>();
        Test.startTest();
        final  Exception_Handling__c dataFacatory = [Select Request__c from Exception_Handling__c where Process_Name__c='HCOHCO1' limit 1];
        final Reltio_CM_HCO_HCO_Inbound_Payload__e payload = (Reltio_CM_HCO_HCO_Inbound_Payload__e) System.JSON.deserialize(dataFacatory.Request__c, Reltio_CM_HCO_HCO_Inbound_Payload__e.class);
        payload.Input_Json__c= payload.Input_Json__c.left(50);
        payloads.add(payload);
        EventBus.publish(payloads);
        Test.getEventBus().deliver();
        for(Account acc : [Select Id,(Select Id from Organization_Communications__r),(Select Id from Organization_E_Invoices__r) from Account limit 500]) {
            acclist.add(acc);
            invoices.addall(acc.Organization_E_Invoices__r);
            comminications.addAll(acc.Organization_Communications__r);
        }
        System.assertEquals(acclist.size(),0,'Account Created');
        System.assertEquals(invoices.size(),0,'Invoice Created');
        System.assertEquals(comminications.size(),0,'Communication Created');
        Test.stopTest();
    } 
}