force-app/main/default/objects/CRM_Order_Event__e/CRM_Order_Event__e.object-meta.xml
<CustomObject>
    <description>publishes platform even on order insert</description>
    <label>CRM Order Event</label>
    <pluralLabel>CRM Order Event</pluralLabel>
</CustomObject>

force-app/main/default/objects/CRM_Order_Event__e/fields/Bill_To_Account__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Account__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>Order Bill to Account details</description>
    <label>Bill To Account</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CRM_Order_Event__e/fields/Bill_To_Contact__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Contact__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>Order details of bill to contact</description>
    <label>Bill To Contact</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CRM_Order_Event__e/fields/Order_Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Event_Type__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>type of event</description>
    <label>Order Event Type</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CRM_Order_Event__e/fields/Order_Id__c.field-meta.xml
<CustomField>
    <fullName>Order_Id__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>Id of the order</description>
    <label>Order Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CRM_Order_Event__e/fields/Payer__c.field-meta.xml
<CustomField>
    <fullName>Payer__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>Payer details of order</description>
    <label>Payer</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CRM_Order_Event__e/fields/Ship_To_Account__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Account__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>Order ship to Account details</description>
    <label>Ship To Account</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CRM_Order_Event__e/fields/Sold_To_Account__c.field-meta.xml
<CustomField>
    <fullName>Sold_To_Account__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>Order sold to Account details</description>
    <label>Sold To Account</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Bill_To_Account__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Account__c</fullName>
    <complianceGroup>None</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>BIll to account details of order</description>
    <label>Bill To Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Bill To Account)</relationshipLabel>
    <relationshipName>Orders3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Payer__c.field-meta.xml
<CustomField>
    <fullName>Payer__c</fullName>
    <complianceGroup>None</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Payer information</description>
    <label>Payer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Payer)</relationshipLabel>
    <relationshipName>Orders2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Ship_To_Account__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Account__c</fullName>
    <complianceGroup>None</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Ship to account</description>
    <label>Ship To Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Ship To Account)</relationshipLabel>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CRM_OrderService.cls
/***********************************************************************************************************************
* Name: CRM_OrderService
* Copyright © Align Tech
* ========================================================================================================================
* Purpose: Publisher of Order platform event
* TestClass : CRM_OrderService
* ========================================================================================================================
* History
*
* VERSION         AUTHOR                          DATE                DETAIL
* 1.0             Sruthi M                        27/02/2024          Class invoked from Order trigger handler
***********************************************************************************************************************/
public with sharing class CRM_OrderService {    
    /**
    * @description : This method publishes order platform event to update owner
    * @parameters : list of orders inserted/updated & trigger context
    */    
    public static void  publishOrderEvent(List<order> oderLst , String trigContext) {                   
        CRM_Order_Event__e event ;                   
        // custom settings/metadata - to get source object/fields and target object/fields                                            
        if(CRM_OrderTriggerHandler.isFirstRun) {         
            final List<CRM_Order_Event__e> orderPELst = new List<CRM_Order_Event__e> ();                              
            for ( Order ord : oderLst ) {  
                event = new CRM_Order_Event__e();           
                event.Order_Id__c = ord.Id;            
                event.Order_Event_Type__c =  trigContext;
                event.Sold_To_Account__c =  ord.AccountId;
                event.Bill_To_Account__c =  ord.Bill_To_Account__c;
                event.Ship_To_Account__c =  ord.Ship_To_Account__c;
                event.Payer__c =  ord.Payer__c;
                event.Bill_To_Contact__c =  ord.BillToContactId;                       
                orderPELst.add(event);   
            }               
            if(!orderPELst.isEmpty()) {                        
                eventbus.publish(orderPELst);                                 
            }           
        }
    }
    
    /**
    * @description : constructor  
    */
    Private CRM_OrderService() {

    }
}