force-app/main/default/objects/Batch_Jobs_Execution__c/Batch_Jobs_Execution__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting would be used to store time against each batch job based on that batch job process will take records for processing.</description>
    <label>Batch Jobs Execution</label>
</CustomObject>

force-app/main/default/objects/Batch_Jobs_Execution__c/fields/Batch_size__c.field-meta.xml
<CustomField>
    <fullName>Batch_size__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>size of the batch job to run</description>
    <label>Batch size</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CM_ScheduleAccountOwnerBatchUpdate.cls
/***********************************************************************************************************************
* Name: CM_ScheduleAccountOwnerBatchUpdate
* Copyright © Align Tech
* ========================================================================================================================
* Purpose: Schedules account owner update batch job
* TestClass : CM_ScheduleAccountOwnerBatchUpdate
* ========================================================================================================================
* History
*
* VERSION         AUTHOR                          DATE                DETAIL
* 1.0             Sruthi M                        13/02/2024          scheduler to update account owner batch job
***********************************************************************************************************************/
public without sharing class CM_ScheduleAccountOwnerBatchUpdate implements Schedulable {
    /**
 	* @description : This Schedules BatchAccountOwnerUpdate.
 	*/
     public void execute(SchedulableContext schCon) { 
        final List<UCB_CustomExceptionWrapper> excpLst;
        final UCB_CustomExceptionWrapper custExcp;
        try {
        	database.executebatch(new CM_AccountOwnerBatchUpdate(),Integer.valueOf(Batch_Jobs_Execution__c.getInstance('Account Ownership Batch').Batch_size__c)); 
            UCB_LoggerService.logger(new List<UCB_Log>{new UCB_Log('Schedule Account Owner Update Batch', 'CM_ScheduleAccountOwnerBatchUpdate', 'Updated Account Owner')});
            UCB_LoggerService.publishLogs();   
        } Catch(Exception excp) {
            custExcp = new UCB_CustomExceptionWrapper();
            excpLst = new List<UCB_CustomExceptionWrapper>();
            custExcp.module = 'Scheduled Account Owner Update Batch';
            custExcp.exceptn =  excp;                       
            excpLst.add(custExcp);            
            UCB_ExceptionService.logException(excpLst);            
        }
    }
}