force-app/main/default/objects/DML_Orchestrator__mdt/DML_Orchestrator__mdt.object-meta.xml
<CustomObject>
    <description>Orchestrating the DMLs on sobjects based on service</description>
    <label>DML Orchestrator</label>
    <pluralLabel>DML Orchestrator</pluralLabel>
</CustomObject>

force-app/main/default/objects/DML_Orchestrator__mdt/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>External Id field to consider on objects</description>
    <label>External ID</label>
    <metadataRelationshipControllingField>DML_Orchestrator__mdt.SObject__c</metadataRelationshipControllingField>
    <referenceTo>EntityParticle</referenceTo>
    <relationshipLabel>Reltio_DML_Orchestrator</relationshipLabel>
    <relationshipName>Reltio_DML_Orchestrator</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/DML_Orchestrator__mdt/fields/Ranking__c.field-meta.xml
<CustomField>
    <fullName>Ranking__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>Ranking used for DML Orchestration</description>
    <label>Ranking</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DML_Orchestrator__mdt/fields/Reltio_CM_Process__c.field-meta.xml
<CustomField>
    <fullName>Reltio_CM_Process__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>Related Customer Master Process name</description>
    <label>Reltio CM Process</label>
    <referenceTo>Reltio_CM_Process__mdt</referenceTo>
    <relationshipLabel>DML Orchestrator</relationshipLabel>
    <relationshipName>Reltio_DML_Orchestrator</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/DML_Orchestrator__mdt/fields/SObject__c.field-meta.xml
<CustomField>
    <fullName>SObject__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>Object Name</description>
    <label>SObject</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Reltio_DML_Orchestrator</relationshipLabel>
    <relationshipName>Reltio_DML_Orchestrator</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Reltio_CM_Process__mdt/Reltio_CM_Process__mdt.object-meta.xml
<CustomObject>
    <description>Reltio-Customer Master Processes</description>
    <label>Reltio CM Process</label>
    <pluralLabel>Reltio CM Processes</pluralLabel>
</CustomObject>

force-app/main/default/objects/Reltio_Field_Mapping__mdt/Reltio_Field_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>Reltio Field Mapping</label>
    <pluralLabel>Reltio Field Mapping</pluralLabel>
</CustomObject>

force-app/main/default/objects/Reltio_Field_Mapping__mdt/fields/Reltio_CM_Process__c.field-meta.xml
<CustomField>
    <fullName>Reltio_CM_Process__c</fullName>
    <complianceGroup>PII</complianceGroup>
    <description>Lookup to Reltio CM Inbound Process</description>
    <label>Reltio CM Process</label>
    <referenceTo>Reltio_CM_Process__mdt</referenceTo>
    <relationshipLabel>Reltio Field Mapping</relationshipLabel>
    <relationshipName>Reltio_Field_Mapping</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Reltio_Field_Mapping__mdt/fields/Source_Field__c.field-meta.xml
<CustomField>
    <fullName>Source_Field__c</fullName>
    <complianceGroup>PII</complianceGroup>
    <description>Source Field</description>
    <inlineHelpText>Source Field</inlineHelpText>
    <label>Source Field</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reltio_Field_Mapping__mdt/fields/Source_Object__c.field-meta.xml
<CustomField>
    <fullName>Source_Object__c</fullName>
    <complianceGroup>PII</complianceGroup>
    <description>Source Object</description>
    <inlineHelpText>Source Object</inlineHelpText>
    <label>Source Object</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Master</fullName>
                <default>true</default>
                <label>Master</label>
            </value>
            <value>
                <fullName>EInvoice</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>SocialMedia</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>License</fullName>
            </value>
            <value>
                <fullName>Roles</fullName>
            </value>
            <value>
                <fullName>LineOfBusiness</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reltio_Field_Mapping__mdt/fields/Source_Parameter__c.field-meta.xml
<CustomField>
    <fullName>Source_Parameter__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>Source Parameter</description>
    <inlineHelpText>Source Parameter</inlineHelpText>
    <label>Source Parameter</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>value</fullName>
                <default>true</default>
                <label>value</label>
            </value>
            <value>
                <fullName>uri</fullName>
            </value>
            <value>
                <fullName>lookupCode</fullName>
            </value>
            <value>
                <fullName>mdmId</fullName>
            </value>
            <value>
                <fullName>startObjectDetails</fullName>
            </value>
            <value>
                <fullName>endObjectDetails</fullName>
            </value>
            <value>
                <fullName>updatedTime</fullName>
            </value>
            <value>
                <fullName>type</fullName>
            </value>
            <value>
                <fullName>objectType</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reltio_Field_Mapping__mdt/fields/Target_Field__c.field-meta.xml
<CustomField>
    <fullName>Target_Field__c</fullName>
    <complianceGroup>PII</complianceGroup>
    <description>Target Field</description>
    <inlineHelpText>Target Field</inlineHelpText>
    <label>Target Field</label>
    <metadataRelationshipControllingField>Reltio_Field_Mapping__mdt.Target_Object__c</metadataRelationshipControllingField>
    <referenceTo>EntityParticle</referenceTo>
    <relationshipLabel>Reltio_Field_Mapping</relationshipLabel>
    <relationshipName>Reltio_Field_Mapping</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Reltio_Field_Mapping__mdt/fields/Target_Object__c.field-meta.xml
<CustomField>
    <fullName>Target_Object__c</fullName>
    <complianceGroup>HIPAA</complianceGroup>
    <description>Target object to consider</description>
    <label>Target Object</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Reltio_Field_Mapping</relationshipLabel>
    <relationshipName>Reltio_Field_Mapping</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/classes/CM_ReltioHandlerService.cls
/***********************************************************************************************************************
 * Name: CM_ReltioHandlerService
 * Copyright © Align Tech
 * ========================================================================================================================
 * Purpose: Subscriber of Reltio  MDM HCO platform event
 * TestClass : CM_ReltioHandlerService
 * ========================================================================================================================
 * History
 *
 * VERSION         AUTHOR                          DATE                DETAIL
 * 1.0             Sruthi M                   11/12/2023          Class invoked from the Subscriber of the Reltio MDM HCO platform event
 ***********************************************************************************************************************/
public with sharing class CM_ReltioHandlerService {
    /**
     * @description : Method to get fieldmappings metadata  
     */
    public Static Map < String, SobjectData> metadataRecords(String relatioProcess) {
        final Map < String, SobjectData > process2Metadata = new Map < String, SobjectData > ();
        Map < Integer, DML_Orchestrator__mdt > dmlMaps;
        Map < String, List < Reltio_Field_Mapping__mdt >> sObj2CusMetadata;
        Map < String, String > srceFld2TargField;
        SobjectData objData;
        final List<String> processList = new List<String>{relatioProcess};
        if(relatioProcess == CM_ReltioConstants.RELTIOHCOPHCO) {
            processList.add(CM_ReltioConstants.RELTIOHCO);   
        } else if(relatioProcess == CM_ReltioConstants.RELTIOHCPHCO) {
            processList.add(CM_ReltioConstants.RELTIOHCO);  
            processList.add(CM_ReltioConstants.RELTIOHCP); 
        } 

        for (Reltio_CM_Process__mdt process: [SELECT DeveloperName, (Select DeveloperName,Source_Parameter__c, Source_Field__c, Source_Object__c,  Target_Field__r.QualifiedApiName, 
                Target_Field__r.DataType, Target_Object__r.QualifiedApiName FROM Reltio_Field_Mapping__r) , 
                (SELECT Ranking__c, External_ID__r.QualifiedApiName, SObject__r.QualifiedApiName FROM Reltio_DML_Orchestrator__r) 
                from Reltio_CM_Process__mdt  where developerName=:processList WITH SECURITY_ENFORCED ]) {
            dmlMaps = new Map < Integer, DML_Orchestrator__mdt > ();
            sObj2CusMetadata = new Map < String, List < Reltio_Field_Mapping__mdt >> ();
            srceFld2TargField = new Map < String, String > ();
            for (Reltio_Field_Mapping__mdt fldMapping: process.Reltio_Field_Mapping__r) {
                if (!sObj2CusMetadata.containsKey(fldMapping.Source_Object__c)) {
                    sObj2CusMetadata.put(fldMapping.Source_Object__c, new List < Reltio_Field_Mapping__mdt > ());
                }
                sObj2CusMetadata.get(fldMapping.Source_Object__c).add(fldMapping);
                srceFld2TargField.put(fldMapping.Source_Object__c, fldMapping.Target_Object__r.QualifiedApiName);
            }
            for (DML_Orchestrator__mdt dmlOrchestrator: process.Reltio_DML_Orchestrator__r) {
                dmlMaps.put((Integer) dmlOrchestrator.Ranking__c, dmlOrchestrator);
            }
            objData = new SobjectData();
            objData.sObj2CusMetadata = sObj2CusMetadata;
            objData.srceFld2TargField = srceFld2TargField;
            objData.dmlMaps = dmlMaps;
            process2Metadata.put(process.developerName, objData);
        }
        return process2Metadata;
    }
    /**  
     * @description : Prepare address street
     */
    public static String addressLine(String accountStreet,String addressLine,Boolean isAddressLine1) {
        String addressStreet;
        if( isAddressLine1) {
            if(!String.isEmpty(addressLine) ) {
                addressStreet= addressLine ;
            }
        } else {
            addressStreet= accountStreet;
            if(!String.isEmpty(addressLine)) {
                addressStreet=accountStreet +  '\n' + addressLine ;
            }
        }
        return addressStreet;
    }
    /**  
     * @description : Merges the data from multiple sobject maps in case of multiple services invoked
     * @parameters : resultmap from object service class & upsertmap from handlerclass
     */
    public Static  Map < String, Map < String, Sobject >> upsertSobjectMap(Map < String, Map < String, Sobject >> resultMap, Map < String, Map < String, Sobject >> upsertMap) {
        for (String str: resultMap.keyset()) {
            if (upsertMap == null || !upsertMap.containsKey(str)) {
                upsertMap.put(str, new map < String, SObject > ());
            }
            upsertMap.get(str).putAll(resultMap.get(str));
        }
        return upsertMap;
    }
    /**
     * @description : Field mappping class
     */
    public class SobjectData {
        /* List of Field Mapping record */
        public Map < String, List < Reltio_Field_Mapping__mdt >> sObj2CusMetadata;
        /* List of Field Mapping record */
        public Map < Integer, DML_Orchestrator__mdt > dmlMaps;
        /*  map of source to target field*/
        public Map < String, String > srceFld2TargField;
    }
    private CM_ReltioHandlerService() {}
}