force-app/main/default/objects/CRM_Asset_Event__e/CRM_Asset_Event__e.object-meta.xml
<CustomObject>
    <description>Pubilshes platform event on asset create/update</description>
    <label>CRM Asset Event</label>
    <pluralLabel>CRM Asset Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/CRM_Asset_Event__e/fields/Asset_Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Asset_Event_Type__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>Describes Type of event Asset create/update</description>
    <label>Asset Event Type</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CRM_AssetEventService.cls
/***********************************************************************************************************************
* Name: CRM_AssetEventService
* Copyright © Align Tech
* ========================================================================================================================
* Purpose: checks asset event context and invokes corresponding actions
* TestClass : CRM_AssetEventService
* ========================================================================================================================
* History
*
* VERSION         AUTHOR                          DATE                DETAIL
* 1.0             Sruthi M                        14/03/2024          Class invoked from Asset platform event subcriber helper.
***********************************************************************************************************************/
public with sharing class CRM_AssetEventService {
    /* type of Asset event */
    final static string CREATE_ASSET = 'Create_Asset';
    /**
    * @description : This method checks the asset platform event type
    * and invokes the corresponding handler actions
    * @parameters : list of asset platform events
    */    
    public static List<CRM_Asset_Event__e> processAssetEvents(List<CRM_Asset_Event__e> eventLst) {                              
        final List<CRM_Asset_Event__e> asstEvntLst = new List<CRM_Asset_Event__e>();
        for( CRM_Asset_Event__e asstEvnt : eventLst ) {                        
            if(asstEvnt.Asset_Event_Type__c == CREATE_ASSET) {
                asstEvntLst.add(asstEvnt);
            }                
        } 
        return asstEvntLst;
    }
    /**
    * @description : constructor  
    */
    private CRM_AssetEventService() { } 
}