force-app/main/default/objects/Customer_Master_Configurations__c/Customer_Master_Configurations__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Customer Master Configurations</description>
    <label>Customer Master Configurations</label>
</CustomObject>

force-app/main/default/objects/Exception_Handling__c/Exception_Handling__c.object-meta.xml
<CustomObject>
    <label>Exception Handling</label>
    <nameField>
        <displayFormat>Exception-{0000000}</displayFormat>
        <label>Exception Handling Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exception Handlings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Exception_Handling__c/fields/Process_Name__c.field-meta.xml
<CustomField>
    <fullName>Process_Name__c</fullName>
    <label>Process Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exception_Handling__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <description>For storing input in a json format</description>
    <label>Request</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Reltio_CM_HCO_HCO_Inbound_Payload__e/Reltio_CM_HCO_HCO_Inbound_Payload__e.object-meta.xml
<CustomObject>
    <description>Reltio Customer Master HCO-HCO Inbound Payload</description>
    <label>Reltio CM HCO_HCO Inbound Payload</label>
    <pluralLabel>Reltio CM HCO_HCO Inbound Payload</pluralLabel>
</CustomObject>

force-app/main/default/objects/Reltio_CM_HCO_HCP_Inbound_Payload__e/Reltio_CM_HCO_HCP_Inbound_Payload__e.object-meta.xml
<CustomObject>
    <description>Reltio Customer Master HCO-HCP Inbound Payload</description>
    <label>Reltio CM HCO_HCP Inbound Payload</label>
    <pluralLabel>Reltio CM HCO_HCP Inbound Payload</pluralLabel>
</CustomObject>

force-app/main/default/objects/Reltio_CM_HCO_HCP_Inbound_Payload__e/fields/Input_Json__c.field-meta.xml
<CustomField>
    <fullName>Input_Json__c</fullName>
    <complianceGroup>PII</complianceGroup>
    <description>Input Json</description>
    <inlineHelpText>Input Json</inlineHelpText>
    <label>Input Json</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Reltio_CM_HCO_Inbound_Payload__e/Reltio_CM_HCO_Inbound_Payload__e.object-meta.xml
<CustomObject>
    <description>Reltio Customer Master HCO Inbound Payload</description>
    <label>Reltio CM HCO Inbound Payload</label>
    <pluralLabel>Reltio CM HCO Inbound Payload</pluralLabel>
</CustomObject>

force-app/main/default/objects/Reltio_CM_HCO_Inbound_Payload__e/fields/Input_Json__c.field-meta.xml
<CustomField>
    <fullName>Input_Json__c</fullName>
    <complianceGroup>PII</complianceGroup>
    <description>Input Json od HCo request</description>
    <inlineHelpText>Input Json od HCo request</inlineHelpText>
    <label>Input Json</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Reltio_CM_HCP_Inbound_Payload__e/Reltio_CM_HCP_Inbound_Payload__e.object-meta.xml
<CustomObject>
    <description>Reltio Customer Master HCP Inbound Payload</description>
    <label>Reltio CM HCP Inbound Payload</label>
    <pluralLabel>Reltio CM HCP Inbound Payload</pluralLabel>
</CustomObject>

force-app/main/default/objects/Reltio_CM_HCP_Inbound_Payload__e/fields/Input_Json__c.field-meta.xml
<CustomField>
    <fullName>Input_Json__c</fullName>
    <complianceGroup>PII</complianceGroup>
    <description>Input Json of HCP Request</description>
    <label>Input Json</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/CM_ReltioInboundPayloadTrigger_Test.cls
/***********************************************************************************************************************
* Name: CM_ReltioInboundPayloadTrigger_Test
* Copyright © Align Tech
* ========================================================================================================================
* Purpose: Subscriber of Reltio  MDM platform event
* TestClass : CM_ReltioInboundPayloadTrigger_Test
* ========================================================================================================================
* History
*
* VERSION         AUTHOR                          DATE                DETAIL
* 1.0             Rohit Jaiswal                   20/10/2023         Test class for Reltio trigger handler
***********************************************************************************************************************/
@isTest
public with sharing class CM_ReltioInboundPayloadTrigger_Test {
    /*****Event Published **************** */
    private static final String EVENT_MSG = 'Event Published';
    
    @testSetup static void setupCustomSettingsData() {        
        Test.loadData(Customer_Master_Configurations__c.sObjectType, 'CustomerMasterConfigurations');
        Test.loadData(Exception_Handling__c.sObjectType, 'ReltioRequests');   }
    @isTest 
    static void reltioHCOService() {
        final List<Reltio_CM_HCO_Inbound_Payload__e> payloads = new List<Reltio_CM_HCO_Inbound_Payload__e>();
        Test.startTest();  
        final Exception_Handling__c dataFacatory = [Select Request__c from Exception_Handling__c where Process_Name__c='ReltioHCOService'];
        final Reltio_CM_HCO_Inbound_Payload__e payload = (Reltio_CM_HCO_Inbound_Payload__e) JSON.deserialize(dataFacatory.Request__c, Reltio_CM_HCO_Inbound_Payload__e.class);
        payloads.add(payload);
        EventBus.publish(payloads);
        Test.getEventBus().deliver();
        System.assertEquals(payloads.size(),1,EVENT_MSG);
        Test.stopTest();
    }
    @isTest 
    static void reltioHCPService() {
        final List<Reltio_CM_HCP_Inbound_Payload__e> payloads = new List<Reltio_CM_HCP_Inbound_Payload__e>();
        Test.startTest();
        final Exception_Handling__c dataFacatory = [Select Request__c from Exception_Handling__c where Process_Name__c='ReltioHCPService'];
        final Reltio_CM_HCP_Inbound_Payload__e payload = (Reltio_CM_HCP_Inbound_Payload__e) JSON.deserialize(dataFacatory.Request__c, Reltio_CM_HCP_Inbound_Payload__e.class);
        payloads.add(payload);
        EventBus.publish(payloads);
        Test.getEventBus().deliver();
        System.assertEquals(payloads.size(),1,EVENT_MSG);
        Test.stopTest();
    }
    @isTest 
    static void reltioHCOHCOService() {
        final  List<Reltio_CM_HCO_HCO_Inbound_Payload__e> payloads = new List<Reltio_CM_HCO_HCO_Inbound_Payload__e>();
        Test.startTest();
        final  Exception_Handling__c dataFacatory = [Select Request__c from Exception_Handling__c where Process_Name__c='ReltioHCOHCOService'];
        final Reltio_CM_HCO_HCO_Inbound_Payload__e payload = (Reltio_CM_HCO_HCO_Inbound_Payload__e) JSON.deserialize(dataFacatory.Request__c, Reltio_CM_HCO_HCO_Inbound_Payload__e.class);
        payloads.add(payload);
        EventBus.publish(payloads);
        Test.getEventBus().deliver();
        System.assertEquals(payloads.size(),1,EVENT_MSG);
        Test.stopTest();
    }
    @isTest 
    static void reltioHCPHCOService() {
        final  List<Reltio_CM_HCO_HCP_Inbound_Payload__e> payloads = new List<Reltio_CM_HCO_HCP_Inbound_Payload__e>();
        Test.startTest();
        final  Exception_Handling__c dataFacatory = [Select Request__c from Exception_Handling__c where Process_Name__c='ReltioHCPHCOService'];
        final Reltio_CM_HCO_HCP_Inbound_Payload__e payload = (Reltio_CM_HCO_HCP_Inbound_Payload__e) JSON.deserialize(dataFacatory.Request__c, Reltio_CM_HCO_HCP_Inbound_Payload__e.class);
        payloads.add(payload);
        EventBus.publish(payloads);
        Test.getEventBus().deliver();
        System.assertEquals(payloads.size(),1,EVENT_MSG);
        Test.stopTest();
    }
    @isTest 
    static void replayService() {
        final  List<Reltio_CM_HCO_HCP_Inbound_Payload__e> payloads = new List<Reltio_CM_HCO_HCP_Inbound_Payload__e>();
        Test.startTest();
        final  Exception_Handling__c dataFacatory = [Select Request__c from Exception_Handling__c where Process_Name__c='ReltioHCPHCOService'];
        final Reltio_CM_HCO_HCP_Inbound_Payload__e payload = (Reltio_CM_HCO_HCP_Inbound_Payload__e) JSON.deserialize(dataFacatory.Request__c, Reltio_CM_HCO_HCP_Inbound_Payload__e.class);
        payload.Input_Json__c= payload.Input_Json__c.left(50);
        payloads.add(payload);
        EventBus.publish(payloads);
        Test.getEventBus().deliver();
        System.assertEquals(payloads.size(),1,EVENT_MSG);
        Test.stopTest();
    }
}