force-app/main/default/objects/Customer_Master_Configurations__c/Customer_Master_Configurations__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Customer Master Configurations</description>
    <label>Customer Master Configurations</label>
</CustomObject>

force-app/main/default/objects/Exception_Handling__c/Exception_Handling__c.object-meta.xml
<CustomObject>
    <label>Exception Handling</label>
    <nameField>
        <displayFormat>Exception-{0000000}</displayFormat>
        <label>Exception Handling Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exception Handlings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Exception_Handling__c/fields/Additional_Info_JSON__c.field-meta.xml
<CustomField>
    <fullName>Additional_Info_JSON__c</fullName>
    <description>Field to store additional info as serialised JSON while logging the exception</description>
    <label>Additional Info JSON</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Exception_Handling__c/fields/Component_Name__c.field-meta.xml
<CustomField>
    <fullName>Component_Name__c</fullName>
    <description>Name of component logging the exception or log</description>
    <label>Component Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exception_Handling__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <description>Field to store the name of business module which logs the exception</description>
    <label>Module</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exception_Handling__c/fields/Process_Name__c.field-meta.xml
<CustomField>
    <fullName>Process_Name__c</fullName>
    <label>Process Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exception_Handling__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <description>For storing input in a json format</description>
    <label>Request</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Organization_Communication__c/Organization_Communication__c.object-meta.xml
<CustomObject>
    <label>Organization Communication</label>
    <nameField>
        <displayFormat>O-{000000}</displayFormat>
        <label>Organization Communication Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organization Communications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Organization_Communication__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>Master-details relationship to Account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Organization Communications</relationshipLabel>
    <relationshipName>Organization_Communications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Organization_E_Invoice__c/Organization_E_Invoice__c.object-meta.xml
<CustomObject>
    <label>Organization E-Invoice</label>
    <nameField>
        <displayFormat>OE-{000000}</displayFormat>
        <label>Organization E-Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organization E-Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Organization_E_Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>This is a Master-Detail relationship to Organization</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Organization E-Invoices</relationshipLabel>
    <relationshipName>Organization_E_Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reltio_CM_HCO_Inbound_Payload__e/Reltio_CM_HCO_Inbound_Payload__e.object-meta.xml
<CustomObject>
    <description>Reltio Customer Master HCO Inbound Payload</description>
    <label>Reltio CM HCO Inbound Payload</label>
    <pluralLabel>Reltio CM HCO Inbound Payload</pluralLabel>
</CustomObject>

force-app/main/default/objects/Reltio_CM_HCO_Inbound_Payload__e/fields/Input_Json__c.field-meta.xml
<CustomField>
    <fullName>Input_Json__c</fullName>
    <complianceGroup>PII</complianceGroup>
    <description>Input Json od HCo request</description>
    <inlineHelpText>Input Json od HCo request</inlineHelpText>
    <label>Input Json</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/CM_ReltioHCOInboundPayloadTrigger_Test.cls
/***********************************************************************************************************************
* Name: CM_ReltioHCOInboundPayloadTrigger_Test
* Copyright © Align Tech
* ========================================================================================================================
* Purpose: Subscriber of Reltio  MDM platform event
* TestClass : CM_ReltioHCOInboundPayloadTrigger_Test
* ========================================================================================================================
* History
*
* VERSION         AUTHOR                          DATE                DETAIL
* 1.0             Rohit Jaiswal                   20/10/2023         Test class for Reltio HCO trigger handler.
***********************************************************************************************************************/
@isTest
public with sharing class CM_ReltioHCOInboundPayloadTrigger_Test {

    @testSetup static void setupCustomSettingsData() {        
        Test.loadData(Customer_Master_Configurations__c.sObjectType, 'CustomerMasterConfigurations');
        Test.loadData(Exception_Handling__c.sObjectType, 'ReltioHCORequests');   
    }
    @isTest 
    static void reltioHCOService() {
        final List<Reltio_CM_HCO_Inbound_Payload__e> payloads = new List<Reltio_CM_HCO_Inbound_Payload__e>();
        final List<Account> acclist = new List<Account>();
        final List<Organization_E_Invoice__c> invoices = new List<Organization_E_Invoice__c>();
        final List<Organization_Communication__c> comminications = new List<Organization_Communication__c>();
        Test.startTest();  
        final Exception_Handling__c dataFacatory = [Select Request__c from Exception_Handling__c where Process_Name__c='HCOTestData' limit 1];
        system.debug('@dataFacatory@'+dataFacatory);
        final Reltio_CM_HCO_Inbound_Payload__e payload = (Reltio_CM_HCO_Inbound_Payload__e) System.JSON.deserialize(dataFacatory.Request__c, Reltio_CM_HCO_Inbound_Payload__e.class);
        payloads.add(payload);
        EventBus.publish(payloads);
        Test.getEventBus().deliver();
        for(Account acc : [Select Id,(Select Id from Organization_Communications__r),(Select Id from Organization_E_Invoices__r) from Account limit 500]) {
            acclist.add(acc);
            invoices.addall(acc.Organization_E_Invoices__r);
            comminications.addAll(acc.Organization_Communications__r);
        }
        system.debug('@rohit1@'+acclist.size());
        system.debug('@rohit2@'+invoices.size());
        system.debug('@rohit3@'+comminications.size());
        for(Exception_Handling__c exp:[Select Id,Additional_Info_JSON__c,Module__c,Component_Name__c,Name from Exception_Handling__c]) {
            System.debug('@rohit@'+exp);
        }
        System.assertEquals(acclist.size(),1,'Account Created');
        System.assertEquals(invoices.size(),1,'Invoice Created');
        System.assertEquals(comminications.size(),3,'Communication Created');
    }
    @isTest 
    static void bulkHCOService() {
        final  List<Reltio_CM_HCO_Inbound_Payload__e> payloads = new List<Reltio_CM_HCO_Inbound_Payload__e>();
        final List<Account> acclist = new List<Account>();
        final List<Organization_E_Invoice__c> invoices = new List<Organization_E_Invoice__c>();
        final List<Organization_Communication__c> comminications = new List<Organization_Communication__c>();
        Reltio_CM_HCO_Inbound_Payload__e payload;
        String request;
        Test.startTest();
        final Exception_Handling__c dataFacatory = [Select Request__c from Exception_Handling__c where Process_Name__c='HCOTestData' limit 1];
        for(Integer i=0; i<2; i++) {
            request = dataFacatory.Request__c;
            request.replaceAll('HCO1','HCO'+i);
            system.debug('@request@'+request);
            payload = (Reltio_CM_HCO_Inbound_Payload__e) System.JSON.deserialize(request, Reltio_CM_HCO_Inbound_Payload__e.class);
            payloads.add(payload);
        }
        EventBus.publish(payloads);
        Test.getEventBus().deliver(); 
        for(Account acc : [Select Id,(Select Id from Organization_Communications__r),(Select Id from Organization_E_Invoices__r) from Account limit 350]) {
            acclist.add(acc);
            invoices.addall(acc.Organization_E_Invoices__r);
            comminications.addAll(acc.Organization_Communications__r);
        }
        System.assertEquals(acclist.size(),20,'Account Created');
        System.assertEquals(invoices.size(),1,'Invoice Created');
        System.assertEquals(comminications.size(),41,'Communication Created');
        Test.stopTest();
    }
    @isTest 
    static void replayService() {
        final  List<Reltio_CM_HCO_Inbound_Payload__e> payloads = new List<Reltio_CM_HCO_Inbound_Payload__e>();
        final List<Account> acclist = new List<Account>();
        final List<Organization_E_Invoice__c> invoices = new List<Organization_E_Invoice__c>();
        final List<Organization_Communication__c> comminications = new List<Organization_Communication__c>();
        Test.startTest();
        final  Exception_Handling__c dataFacatory = [Select Request__c from Exception_Handling__c where Process_Name__c='HCO2' limit 1];
        final Reltio_CM_HCO_Inbound_Payload__e payload = (Reltio_CM_HCO_Inbound_Payload__e) System.JSON.deserialize(dataFacatory.Request__c, Reltio_CM_HCO_Inbound_Payload__e.class);
        payload.Input_Json__c= payload.Input_Json__c.left(50);
        payloads.add(payload);
        EventBus.publish(payloads);
        Test.getEventBus().deliver();
        for(Account acc : [Select Id,(Select Id from Organization_Communications__r),(Select Id from Organization_E_Invoices__r) from Account limit 500]) {
            acclist.add(acc);
            invoices.addall(acc.Organization_E_Invoices__r);
            comminications.addAll(acc.Organization_Communications__r);
        }
        System.assertEquals(acclist.size(),0,'Account Created');
        System.assertEquals(invoices.size(),0,'Invoice Created');
        System.assertEquals(comminications.size(),0,'Communication Created');
        Test.stopTest();
    } 
}