force-app/main/default/objects/Customer_Master_Configurations__c/Customer_Master_Configurations__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Customer Master Configurations</description>
    <label>Customer Master Configurations</label>
</CustomObject>

force-app/main/default/objects/Educational_Detail__c/Educational_Detail__c.object-meta.xml
<CustomObject>
    <description>Education details of HCP</description>
    <label>Educational Detail</label>
    <nameField>
        <displayFormat>E-{000000}</displayFormat>
        <label>Educational Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Educational Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Educational_Detail__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>Lookup to contact</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Educational Details</relationshipLabel>
    <relationshipName>Educational_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Exception_Handling__c/Exception_Handling__c.object-meta.xml
<CustomObject>
    <label>Exception Handling</label>
    <nameField>
        <displayFormat>Exception-{0000000}</displayFormat>
        <label>Exception Handling Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exception Handlings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Exception_Handling__c/fields/Process_Name__c.field-meta.xml
<CustomField>
    <fullName>Process_Name__c</fullName>
    <label>Process Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exception_Handling__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <description>For storing input in a json format</description>
    <label>Request</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/License_Information__c/License_Information__c.object-meta.xml
<CustomObject>
    <label>License Information</label>
    <nameField>
        <displayFormat>L-{000000}</displayFormat>
        <label>License Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>License Informations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/License_Information__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>Lookup to Contact</description>
    <inlineHelpText>Lookup to Contact</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>License Informations</relationshipLabel>
    <relationshipName>License_Informations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Person_Communication__c/Person_Communication__c.object-meta.xml
<CustomObject>
    <label>Person Communication</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Person Communication Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Person Communications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Person_Communication__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>Master-details relationship to Contact</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Person Communications</relationshipLabel>
    <relationshipName>Person_Communications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reltio_CM_HCP_Inbound_Payload__e/Reltio_CM_HCP_Inbound_Payload__e.object-meta.xml
<CustomObject>
    <description>Reltio Customer Master HCP Inbound Payload</description>
    <label>Reltio CM HCP Inbound Payload</label>
    <pluralLabel>Reltio CM HCP Inbound Payload</pluralLabel>
</CustomObject>

force-app/main/default/objects/Reltio_CM_HCP_Inbound_Payload__e/fields/Input_Json__c.field-meta.xml
<CustomField>
    <fullName>Input_Json__c</fullName>
    <complianceGroup>PII</complianceGroup>
    <description>Input Json of HCP Request</description>
    <label>Input Json</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/CM_ReltioHCPInboundPayloadTrigger_Test.cls
/***********************************************************************************************************************
* Name: CM_ReltioHCPInboundPayloadTrigger_Test
* Copyright © Align Tech
* ========================================================================================================================
* Purpose: Subscriber of Reltio  MDM platform event
* TestClass : CM_ReltioHCPInboundPayloadTrigger_Test
* ========================================================================================================================
* History
*
* VERSION         AUTHOR                          DATE                DETAIL
* 1.0             Rohit Jaiswal                   20/10/2023         Test class for Reltio HCO trigger handler.
***********************************************************************************************************************/
@isTest
public with sharing class CM_ReltioHCPInboundPayloadTrigger_Test {

    @testSetup static void setupCustomSettingsData() {        
        Test.loadData(Customer_Master_Configurations__c.sObjectType, 'CustomerMasterConfigurations');
        Test.loadData(Exception_Handling__c.sObjectType, 'ReltioHCPRequests');   
    }
    @isTest 
    static void reltioHCPService() {
        final List<Reltio_CM_HCP_Inbound_Payload__e> payloads = new List<Reltio_CM_HCP_Inbound_Payload__e>();
        final List<Contact> conList = new List<Contact>();
        final List<Person_Communication__c> communications = new List<Person_Communication__c>();
        final List<Educational_Detail__c> eduDetails = new List<Educational_Detail__c>();
        final List<License_Information__c> lincences = new List<License_Information__c>();
        Test.startTest();  
        final Exception_Handling__c dataFacatory = [Select Request__c from Exception_Handling__c where Process_Name__c='HCP1' limit 1];
        final Reltio_CM_HCP_Inbound_Payload__e payload = (Reltio_CM_HCP_Inbound_Payload__e) System.JSON.deserialize(dataFacatory.Request__c, Reltio_CM_HCP_Inbound_Payload__e.class);
        payloads.add(payload);
        EventBus.publish(payloads);
        Test.getEventBus().deliver();
        for(Contact con : [Select Id,(Select Id from Educational_Details__r),(Select Id from Person_Communications__r),
                        (Select Id from License_Informations__r) from Contact limit 1]) {
            conList.add(con);
            communications.addall(con.Person_Communications__r);
            eduDetails.addAll(con.Educational_Details__r);
            lincences.addAll(con.License_Informations__r);
        }
        System.assertEquals(eduDetails.size(),1,'Education details Created');
        System.assertEquals(lincences.size(),1,'Licences Created');
        System.assertEquals(communications.size(),3,'Communication Created');
        Test.stopTest();
    }
    @isTest 
    static void bulkHCPService() {
        final  List<Reltio_CM_HCP_Inbound_Payload__e> payloads = new List<Reltio_CM_HCP_Inbound_Payload__e>();
        final List<Contact> conList = new List<Contact>();
        final List<Person_Communication__c> communications = new List<Person_Communication__c>();
        final List<Educational_Detail__c> eduDetails = new List<Educational_Detail__c>();
        final List<License_Information__c> lincences = new List<License_Information__c>();
        Reltio_CM_HCP_Inbound_Payload__e payload;
        Test.startTest();
        for(Exception_Handling__c dataFacatory : [Select Request__c from Exception_Handling__c  limit 300] ) {
            payload = (Reltio_CM_HCP_Inbound_Payload__e) System.JSON.deserialize(dataFacatory.Request__c, Reltio_CM_HCP_Inbound_Payload__e.class);
            payloads.add(payload);
        }
        EventBus.publish(payloads);
        Test.getEventBus().deliver(); 
        for(Contact con : [Select Id,(Select Id from Educational_Details__r),
                (Select Id from Person_Communications__r),(Select Id from License_Informations__r) from Contact Limit 500]) {
            conList.add(con);
            communications.addall(con.Person_Communications__r);
            eduDetails.addAll(con.Educational_Details__r);
            lincences.addAll(con.License_Informations__r);
        }
        System.assertEquals(eduDetails.size(),0,'Education details Created');
        System.assertEquals(lincences.size(),0,'Licences Created');
        System.assertEquals(communications.size(),0,'Communication Created');
        Test.stopTest();
    }
    @isTest 
    static void replayService() {
        final  List<Reltio_CM_HCP_Inbound_Payload__e> payloads = new List<Reltio_CM_HCP_Inbound_Payload__e>();
        final List<Contact> conList = new List<Contact>();
        final List<Person_Communication__c> communications = new List<Person_Communication__c>();
        final List<Educational_Detail__c> eduDetails = new List<Educational_Detail__c>();
        final List<License_Information__c> lincences = new List<License_Information__c>();
        Test.startTest();
        final  Exception_Handling__c dataFacatory = [Select Request__c from Exception_Handling__c where Process_Name__c='HCP2' limit 1];
        final Reltio_CM_HCP_Inbound_Payload__e payload = (Reltio_CM_HCP_Inbound_Payload__e) System.JSON.deserialize(dataFacatory.Request__c, Reltio_CM_HCP_Inbound_Payload__e.class);
        payload.Input_Json__c= payload.Input_Json__c.left(50);
        payloads.add(payload);
        EventBus.publish(payloads);
        Test.getEventBus().deliver();
        for(Contact con : [Select Id,(Select Id from Educational_Details__r),(Select Id from Person_Communications__r),(Select Id from License_Informations__r) from Contact limit 1]) {
            conList.add(con);
            communications.addall(con.Person_Communications__r);
            eduDetails.addAll(con.Educational_Details__r);
            lincences.addAll(con.License_Informations__r);
        }
        System.assertEquals(eduDetails.size(),0,'Education details Created');
        System.assertEquals(lincences.size(),0,'Licences Created');
        System.assertEquals(communications.size(),0,'Communication Created');
        Test.stopTest();
    } 
}