force-app/main/default/objects/Account/fields/Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_1__c</fullName>
    <complianceGroup>PII</complianceGroup>
    <description>This will store Address Line 1</description>
    <label>Address Line 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_2__c</fullName>
    <businessOwnerGroup>Customer_Master_Owners</businessOwnerGroup>
    <complianceGroup>PII</complianceGroup>
    <description>Created this to Address Line 2</description>
    <label>Address Line 2</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Address_Line_3__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_3__c</fullName>
    <businessOwnerGroup>Customer_Master_Owners</businessOwnerGroup>
    <complianceGroup>PII</complianceGroup>
    <description>Address Line 3</description>
    <inlineHelpText>Address Line 3</inlineHelpText>
    <label>Address Line 3</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Address_Line_4__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_4__c</fullName>
    <businessOwnerGroup>Customer_Master_Owners</businessOwnerGroup>
    <complianceGroup>PII</complianceGroup>
    <description>Address Line 4</description>
    <inlineHelpText>Address Line 4</inlineHelpText>
    <label>Address Line 4</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Company_Email__c.field-meta.xml
<CustomField>
    <fullName>Company_Email__c</fullName>
    <complianceGroup>PII</complianceGroup>
    <description>This is primary email of an organization</description>
    <inlineHelpText>This is the MDM unique identifier</inlineHelpText>
    <label>Company Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/MDM_Id__c.field-meta.xml
<CustomField>
    <fullName>MDM_Id__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>This is the MDM unique identifier</description>
    <externalId>true</externalId>
    <inlineHelpText>This is the MDM unique identifier</inlineHelpText>
    <label>MDM Id</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Native_Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Native_Address_Line_2__c</fullName>
    <complianceGroup>PII</complianceGroup>
    <description>Native Address Line 2</description>
    <inlineHelpText>Native Address Line 2</inlineHelpText>
    <label>Native Address Line 2</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Native_Address_Line_3__c.field-meta.xml
<CustomField>
    <fullName>Native_Address_Line_3__c</fullName>
    <complianceGroup>PII</complianceGroup>
    <description>Native Address Line 3</description>
    <inlineHelpText>Native Address Line 3</inlineHelpText>
    <label>Native Address Line 3</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Organization_Communication__c/Organization_Communication__c.object-meta.xml
<CustomObject>
    <label>Organization Communication</label>
    <nameField>
        <displayFormat>O-{000000}</displayFormat>
        <label>Organization Communication Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organization Communications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Organization_Communication__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>Master-details relationship to Account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Organization Communications</relationshipLabel>
    <relationshipName>Organization_Communications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Organization_Communication__c/fields/MDM_Id__c.field-meta.xml
<CustomField>
    <fullName>MDM_Id__c</fullName>
    <businessOwnerGroup>Customer_Master_Owners</businessOwnerGroup>
    <complianceGroup>None</complianceGroup>
    <description>Unique identifier</description>
    <externalId>true</externalId>
    <label>MDM Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Organization_Communication__c/fields/Subtype__c.field-meta.xml
<CustomField>
    <fullName>Subtype__c</fullName>
    <businessOwnerGroup>Customer_Master_Owners</businessOwnerGroup>
    <complianceGroup>None</complianceGroup>
    <description>This is the subtype corresponding to Type field</description>
    <label>Subtype</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary Phone</fullName>
            </value>
            <value>
                <fullName>Secondary Phone</fullName>
            </value>
            <value>
                <fullName>Fax</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Other1</fullName>
            </value>
            <value>
                <fullName>Other2</fullName>
            </value>
            <value>
                <fullName>Other3</fullName>
            </value>
            <value>
                <fullName>Other4</fullName>
            </value>
            <value>
                <fullName>Primary Email</fullName>
            </value>
            <value>
                <fullName>Secondary Email</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>Instagram</fullName>
            </value>
            <value>
                <fullName>WeChat</fullName>
            </value>
            <value>
                <fullName>Whatsapp</fullName>
            </value>
            <value>
                <fullName>LinkedIn</fullName>
            </value>
            <value>
                <fullName>Pinterest</fullName>
            </value>
            <value>
                <fullName>Twitter</fullName>
            </value>
            <value>
                <fullName>KakaoTalk</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Organization_Communication__c/fields/TimeStamp_Decimal__c.field-meta.xml
<CustomField>
    <fullName>TimeStamp_Decimal__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>Timestamp in decimal</description>
    <inlineHelpText>Timestamp in decimal</inlineHelpText>
    <label>TimeStamp Decimal</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Organization_Communication__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <complianceGroup>PII</complianceGroup>
    <description>This contains the detailed information for the corresponding Type and Subtype</description>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Organization_E_Invoice__c/Organization_E_Invoice__c.object-meta.xml
<CustomObject>
    <label>Organization E-Invoice</label>
    <nameField>
        <displayFormat>OE-{000000}</displayFormat>
        <label>Organization E-Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organization E-Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Organization_E_Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>This is a Master-Detail relationship to Organization</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Organization E-Invoices</relationshipLabel>
    <relationshipName>Organization_E_Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Organization_E_Invoice__c/fields/MDM_Id__c.field-meta.xml
<CustomField>
    <fullName>MDM_Id__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>This is the MDM unique identifier</description>
    <externalId>true</externalId>
    <label>MDM Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CM_ReltioHCOService.cls
/***********************************************************************************************************************
 * Name: CM_ReltioHCOService
 * Copyright © Align Tech
 * ========================================================================================================================
 * Purpose: Service class handles Account Creation, Service invoked from platform event trigger handler
 * TestClass : CM_ReltioHCOService
 * ========================================================================================================================
 * History
 *
 * VERSION         AUTHOR                          DATE                DETAIL
 * 1.0             Rohit Jaiswal                   20/10/2023          Account Creation Service 
 ***********************************************************************************************************************/
public with sharing class CM_ReltioHCOService {
    /* Account String */
    final static string ACCOUNTSTRING = 'Account';
    /**    
     * @description :  Method to parse input json and get Account data
     * @Parameters : input json, process name from platfrom event
     */
    public static Map < String, Map < String, Sobject >> upsertHCOServices(String inputJson, Map < String, CM_ReltioHandlerService.SobjectData > process2Metadata) {
        final Map < String, Map < String, Map < String, Object >>> key2value = CM_JSONParser.objectJsonParsers(inputJson, process2Metadata.get(CM_ReltioConstants.RELTIOHCO));
        return upsertHCOSelector(key2value);
    }
    /**     
     * @description : Retrieves data of Account and related Sobjects
     */
    public static Map < String, Map < String, Sobject >> upsertHCOSelector(Map < String, Map < String, Map < String, Object >>> key2value) {
        final Map < String, Map < String, Sobject >> resultMap = new Map < String, Map < String, Sobject >> ();
        Map < String, Organization_Communication__c > cusCommunication = new Map < String, Organization_Communication__c > ();
        final Map < String, Account > accountMap = new Map < String, Account > ();

        Account account = new Account();
        if (key2value.containsKey(ACCOUNTSTRING)) {
            account = CM_AccountService.upsertAccount(key2value.get(ACCOUNTSTRING));
        }

        if (key2value.containsKey('Organization_Communication__c')) {
            cusCommunication = CM_CustomerInformationService.upsertCommInformation(key2value.get('Organization_Communication__c'), account);
            resultMap.put('Organization_Communication__c', cusCommunication);
        }

        if (key2value.containsKey('Organization_E_Invoice__c')) {
            final Map < String, Organization_E_Invoice__c > cosInvoiceMap = CM_CustomerInvoiceService.upsertCustomerInvoice(key2value.get('Organization_E_Invoice__c'), account);
            resultMap.put('Organization_E_Invoice__c', cosInvoiceMap);
        }

        //update phone and email in the Account from Customer Communication
        account = getAccountList(account, cusCommunication.values());
        accountMap.put(account.MDM_Id__c, account);
        resultMap.put(ACCOUNTSTRING, accountMap);

        return resultMap;
    }
    /**     
     * @description : Populates Account primary phone, email
     */
    private static Account getAccountList(Account account, List < Organization_Communication__c > cusInformList) {
        for (Organization_Communication__c cusInformation: cusInformList) {
            if (cusInformation.Subtype__c == CM_ReltioConstants.PRIMARYPHONE) {
                account.Phone = cusInformation.value__c;
            }
            if (cusInformation.Subtype__c == CM_ReltioConstants.PRIMARYEMAIL) {
                account.Company_Email__c = cusInformation.value__c;
            }
        }
        account.ShippingStreet = CM_ReltioHandlerService.addressLine(account.ShippingStreet,account.Address_Line_1__c,true);
        account.ShippingStreet = CM_ReltioHandlerService.addressLine(account.ShippingStreet,account.Address_Line_2__c,false);
        account.ShippingStreet = CM_ReltioHandlerService.addressLine(account.ShippingStreet,account.Address_Line_3__c,false);
        account.ShippingStreet = CM_ReltioHandlerService.addressLine(account.ShippingStreet,account.Address_Line_4__c,false);

        account.Native_Address__Street__s  = CM_ReltioHandlerService.addressLine(account.Native_Address__Street__s,account.Native_Address_Line_1__c,true);
        account.Native_Address__Street__s  = CM_ReltioHandlerService.addressLine(account.Native_Address__Street__s ,account.Native_Address_Line_2__c,false);
        account.Native_Address__Street__s  = CM_ReltioHandlerService.addressLine(account.Native_Address__Street__s ,account.Native_Address_Line_3__c,false);
        account.Native_Address__Street__s  = CM_ReltioHandlerService.addressLine(account.Native_Address__Street__s ,account.Native_Address_Line_4__c,false);

        return account;
    }   
    public  static Map<String, Map < String, Sobject >> getOldAccountMap(Map <String, Map < String, Sobject >> upsertNewMap) {
        Set<String> recordId = upsertNewMap.get(ACCOUNTSTRING).keyset();
        final Map <String, Map < String, Sobject >> upsertOldMap = new Map < String, Map < String, Sobject >> ();
        upsertOldMap.put(ACCOUNTSTRING,new Map <String, Sobject>());  
        upsertOldMap.put('Organization_Communication__c',new Map <String, Sobject>());  
        upsertOldMap.put('Organization_E_Invoice__c',new Map <String, Sobject>());  
        for(Account acc : [Select Id,MDM_Id__c,TimeStamp_Decimal__c,
                        (Select Id,MDM_Id__c,Account__r.MDM_Id__c,TimeStamp_Decimal__c from Organization_Communications__r),
                        (Select Id,MDM_Id__c,Account__r.MDM_Id__c,TimeStamp_Decimal__c from Organization_E_Invoices__r) 
                        from Account where MDM_Id__c = :recordId with SECURITY_ENFORCED]) {
            upsertOldMap.get(ACCOUNTSTRING).put(acc.MDM_Id__c,acc);
            for(Organization_Communication__c communication: acc.Organization_Communications__r) {
                upsertOldMap.get('Organization_Communication__c').put(communication.MDM_Id__c,communication);  
            }
            for(Organization_E_Invoice__c invoice: acc.Organization_E_Invoices__r) {
                upsertOldMap.get('Organization_E_Invoice__c').put(invoice.MDM_Id__c,invoice); 
            }
        }
        return upsertOldMap;
    }
    private CM_ReltioHCOService() {}
}