force-app/main/default/objects/Account/fields/Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_1__c</fullName>
    <complianceGroup>PII</complianceGroup>
    <description>This will store Address Line 1</description>
    <label>Address Line 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_2__c</fullName>
    <businessOwnerGroup>Customer_Master_Owners</businessOwnerGroup>
    <complianceGroup>PII</complianceGroup>
    <description>Created this to Address Line 2</description>
    <label>Address Line 2</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Address_Line_3__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_3__c</fullName>
    <businessOwnerGroup>Customer_Master_Owners</businessOwnerGroup>
    <complianceGroup>PII</complianceGroup>
    <description>Address Line 3</description>
    <inlineHelpText>Address Line 3</inlineHelpText>
    <label>Address Line 3</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Address_Line_4__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_4__c</fullName>
    <businessOwnerGroup>Customer_Master_Owners</businessOwnerGroup>
    <complianceGroup>PII</complianceGroup>
    <description>Address Line 4</description>
    <inlineHelpText>Address Line 4</inlineHelpText>
    <label>Address Line 4</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/MDM_Id__c.field-meta.xml
<CustomField>
    <fullName>MDM_Id__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>This is the MDM unique identifier</description>
    <externalId>true</externalId>
    <inlineHelpText>This is the MDM unique identifier</inlineHelpText>
    <label>MDM Id</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Native_Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Native_Address_Line_2__c</fullName>
    <complianceGroup>PII</complianceGroup>
    <description>Native Address Line 2</description>
    <inlineHelpText>Native Address Line 2</inlineHelpText>
    <label>Native Address Line 2</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Native_Address_Line_3__c.field-meta.xml
<CustomField>
    <fullName>Native_Address_Line_3__c</fullName>
    <complianceGroup>PII</complianceGroup>
    <description>Native Address Line 3</description>
    <inlineHelpText>Native Address Line 3</inlineHelpText>
    <label>Native Address Line 3</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_1__c</fullName>
    <complianceGroup>PII</complianceGroup>
    <description>This will store Address Line 1 of Person</description>
    <label>Address Line 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_2__c</fullName>
    <complianceGroup>PII</complianceGroup>
    <description>This will store Address line 2 details of person</description>
    <label>Address Line 2</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Address_Line_3__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_3__c</fullName>
    <complianceGroup>PII</complianceGroup>
    <description>This will store Address line 3 details of person</description>
    <label>Address Line 3</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Address_Line_4__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_4__c</fullName>
    <complianceGroup>PII</complianceGroup>
    <description>This will store address line4 details of person</description>
    <label>Address Line 4</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Native_Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Native_Address_Line_1__c</fullName>
    <complianceGroup>PII</complianceGroup>
    <description>Native Address Line 1</description>
    <inlineHelpText>Native Address Line 1</inlineHelpText>
    <label>Native Address Line 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Native_Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Native_Address_Line_2__c</fullName>
    <complianceGroup>PII</complianceGroup>
    <description>Native Address Line 2</description>
    <inlineHelpText>Native Address Line 2</inlineHelpText>
    <label>Native Address Line 2</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Native_Address_Line_3__c.field-meta.xml
<CustomField>
    <fullName>Native_Address_Line_3__c</fullName>
    <complianceGroup>PII</complianceGroup>
    <description>Native Address Line 3</description>
    <inlineHelpText>Native Address Line 3</inlineHelpText>
    <label>Native Address Line 3</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Native_Address_Line_4__c.field-meta.xml
<CustomField>
    <fullName>Native_Address_Line_4__c</fullName>
    <complianceGroup>PII</complianceGroup>
    <description>Native Address Line 4</description>
    <inlineHelpText>Native Address Line 4</inlineHelpText>
    <label>Native Address Line 4</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Educational_Detail__c/Educational_Detail__c.object-meta.xml
<CustomObject>
    <description>Education details of HCP</description>
    <label>Educational Detail</label>
    <nameField>
        <displayFormat>E-{000000}</displayFormat>
        <label>Educational Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Educational Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Educational_Detail__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>Lookup to contact</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Educational Details</relationshipLabel>
    <relationshipName>Educational_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Educational_Detail__c/fields/MDM_Id__c.field-meta.xml
<CustomField>
    <fullName>MDM_Id__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>Education details</description>
    <externalId>true</externalId>
    <label>MDM Id</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Educational_Detail__c/fields/TimeStamp_Decimal__c.field-meta.xml
<CustomField>
    <fullName>TimeStamp_Decimal__c</fullName>
    <description>Timestamp in decimal</description>
    <inlineHelpText>Timestamp in decimal</inlineHelpText>
    <label>TimeStamp Decimal</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/License_Information__c/License_Information__c.object-meta.xml
<CustomObject>
    <label>License Information</label>
    <nameField>
        <displayFormat>L-{000000}</displayFormat>
        <label>License Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>License Informations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/License_Information__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>Lookup to Contact</description>
    <inlineHelpText>Lookup to Contact</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>License Informations</relationshipLabel>
    <relationshipName>License_Informations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/License_Information__c/fields/MDM_Id__c.field-meta.xml
<CustomField>
    <fullName>MDM_Id__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>License Information of HCP</description>
    <externalId>true</externalId>
    <label>MDM Id</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person_Communication__c/Person_Communication__c.object-meta.xml
<CustomObject>
    <label>Person Communication</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Person Communication Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Person Communications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Person_Communication__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>Master-details relationship to Contact</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Person Communications</relationshipLabel>
    <relationshipName>Person_Communications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Person_Communication__c/fields/MDM_Id__c.field-meta.xml
<CustomField>
    <fullName>MDM_Id__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>Unique identifier</description>
    <externalId>true</externalId>
    <label>MDM Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person_Communication__c/fields/TimeStamp_Decimal__c.field-meta.xml
<CustomField>
    <fullName>TimeStamp_Decimal__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>Timestamp in decimal</description>
    <inlineHelpText>Timestamp in decimal</inlineHelpText>
    <label>TimeStamp Decimal</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Person_Communication__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <complianceGroup>PII</complianceGroup>
    <description>This contains the detailed information for the corresponding Type and Subtype</description>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CM_ReltioHCPService.cls
/***********************************************************************************************************************
 * Name: CM_ReltioHCPService
 * Copyright © Align Tech
 * ========================================================================================================================
 * Purpose: Service class handles Contact Creation, Service invoked from platform event trigger handler
 * TestClass : CM_ReltioHCPService
 * ========================================================================================================================
 * History
 *
 * VERSION         AUTHOR                          DATE                DETAIL
 * 1.0             Sruthi M                   07/11/2023          Contact Creation Service 
 ***********************************************************************************************************************/
public with sharing class CM_ReltioHCPService {
    /**    
     * @description :  Method to parse input json and get Contact data
     * Parameters : input json, process name from platfrom event
     */
    public static Map < String, Map < String, Sobject >> upsertHCPServices(String inputJson, Map < String, CM_ReltioHandlerService.SobjectData > process2Metadata) {        
        final Map < String, Map < String, Map < String, Object >>> key2value = CM_JSONParser.objectJsonParsers(inputJson, process2Metadata.get(CM_ReltioConstants.RELTIOHCP));
        return upsertHCPSelector(key2value);
    }

    /**     
     * @description : Retrieves data of Contact and related sobjects
     */
    public static Map < String, Map < String, Sobject >> upsertHCPSelector(Map < String, Map < String, Map < String, Object >>> key2value) {
        final Map < String, Map < String, Sobject >> resultMap = new Map < String, Map < String, Sobject >> ();
        Contact contact = CM_ContactService.upsertContact(key2value.get('Contact'));
        Map < String, Person_Communication__c > commInfoMap = new Map < String, Person_Communication__c > ();
        final Map < String, Contact > contactMap = new Map < String, Contact > ();

        //person communication information
        if (key2value.containsKey('Person_Communication__c')) {
            commInfoMap = CM_PersonCommunicationService.upsertHCPcommunicationInfo(key2value.get('Person_Communication__c'), contact);
            resultMap.put('Person_Communication__c', commInfoMap);
        }

        if (key2value.containsKey('Educational_Detail__c')) {
            final Map < String, Educational_Detail__c > hcpEduMap = CM_EducationalDetailsService.upsertEducationalDetails(key2value.get('Educational_Detail__c'), contact);
            resultMap.put('Educational_Detail__c', hcpEduMap);
        }

        if (key2value.containsKey('License_Information__c')) {
            final Map < String, License_Information__c > hcpLicenseInfoMap = CM_LicenseInformationService.upsertLicenseInformationDetails(key2value.get('License_Information__c'), contact);
            resultMap.put('License_Information__c', hcpLicenseInfoMap);
        }

        //update phone and email in the contact from Communication Information
        contact = getContactList(contact, commInfoMap.values());
        contactMap.put(contact.MDM_Id__c, contact);
        resultMap.put('Contact', contactMap);
        return resultMap;
    }
    /**     
     * @description : Populates Contact primary phone, email
     */
    private static contact getContactList(Contact contact, List < Person_Communication__c > personInfoList) {
        for (Person_Communication__c hcpInfo: personInfoList) {
            if (hcpInfo.Subtype__c == CM_ReltioConstants.PRIMARYPHONE) {
                contact.Phone = hcpInfo.value__c;
            }
            if (hcpInfo.Subtype__c == CM_ReltioConstants.PRIMARYEMAIL) {
                contact.Email = hcpInfo.value__c;
            }
        }
        contact.MailingStreet = CM_ReltioHandlerService.addressLine(contact.MailingStreet,contact.Address_Line_1__c,true);
        contact.MailingStreet = CM_ReltioHandlerService.addressLine(contact.MailingStreet,contact.Address_Line_2__c,false);
        contact.MailingStreet = CM_ReltioHandlerService.addressLine(contact.MailingStreet,contact.Address_Line_3__c,false);
        contact.MailingStreet = CM_ReltioHandlerService.addressLine(contact.MailingStreet,contact.Address_Line_4__c,false);

        contact.Native_Address__Street__s  = CM_ReltioHandlerService.addressLine(contact.Native_Address__Street__s,contact.Native_Address_Line_1__c,true);
        contact.Native_Address__Street__s  = CM_ReltioHandlerService.addressLine(contact.Native_Address__Street__s ,contact.Native_Address_Line_2__c,false);
        contact.Native_Address__Street__s  = CM_ReltioHandlerService.addressLine(contact.Native_Address__Street__s ,contact.Native_Address_Line_3__c,false);
        contact.Native_Address__Street__s  = CM_ReltioHandlerService.addressLine(contact.Native_Address__Street__s ,contact.Native_Address_Line_4__c,false);
        return contact;
    }
    public  static Map<String, Map < String, Sobject >> getOldContactMap(Map <String, Map < String, Sobject >> upsertNewMap) {
        final Set<String> recordId = upsertNewMap.get('Contact').keyset();
        final Map <String, Map < String, Sobject >> upsertOldMap = new Map < String, Map < String, Sobject >> ();
        upsertOldMap.put('Contact',new Map <String, Sobject>());  
        upsertOldMap.put('Educational_Detail__c',new Map <String, Sobject>());  
        upsertOldMap.put('Person_Communication__c',new Map <String, Sobject>());  
        upsertOldMap.put('License_Information__c',new Map <String, Sobject>()); 
        for(Contact con : [Select Id,MDM_Id__c,TimeStamp_Decimal__c,Account.MDM_Id__c,
            (Select Id,MDM_Id__c,Contact__r.MDM_Id__c,TimeStamp_Decimal__c from Educational_Details__r),
            (Select Id,MDM_Id__c,Contact__r.MDM_Id__c,TimeStamp_Decimal__c from Person_Communications__r),
            (Select Id,MDM_Id__c,Contact__r.MDM_Id__c,TimeStamp_Decimal__c from License_Informations__r) 
            from Contact where MDM_Id__c = :recordId with SECURITY_ENFORCED]) {
            upsertOldMap.get('Contact').put(con.MDM_Id__c,con);
            for(Educational_Detail__c education : con.Educational_Details__r) {
                upsertOldMap.get('Educational_Detail__c').put(education.MDM_Id__c,education);  
            }
            for(Person_Communication__c communication: con.Person_Communications__r) {
                upsertOldMap.get('Person_Communication__c').put(communication.MDM_Id__c,communication); 
            }
            for(License_Information__c licence: con.License_Informations__r) {
                upsertOldMap.get('License_Information__c').put(licence.MDM_Id__c,licence); 
            }
        }
        return upsertOldMap;
    }
    private CM_ReltioHCPService() {}
}