force-app/main/default/objects/Account/fields/MDM_Id__c.field-meta.xml
<CustomField>
    <fullName>MDM_Id__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>This is the MDM unique identifier</description>
    <externalId>true</externalId>
    <inlineHelpText>This is the MDM unique identifier</inlineHelpText>
    <label>MDM Id</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <businessOwnerGroup>Customer_Master_Owners</businessOwnerGroup>
    <complianceGroup>None</complianceGroup>
    <description>This field specifies the current status of an organization</description>
    <inlineHelpText>This field specifies the current status of an organization</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AccountContactRelation/fields/AccountContact_Id__c.field-meta.xml
<CustomField>
    <fullName>AccountContact_Id__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>MDM AccountContact Id</description>
    <externalId>true</externalId>
    <inlineHelpText>MDM AccountContact Id</inlineHelpText>
    <label>AccountContact Id</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountContactRelation/fields/MDM_Id__c.field-meta.xml
<CustomField>
    <fullName>MDM_Id__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>This field stores unique MDM identifier for HCO-HCP relationship</description>
    <externalId>true</externalId>
    <inlineHelpText>This field stores unique MDM identifier for HCO-HCP relationship</inlineHelpText>
    <label>MDM Id</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountContactRelation/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>This field stores current status for HCO-HCP relationship</description>
    <inlineHelpText>This field stores cusrrent status for HCO-HCP relationship</inlineHelpText>
    <label>Relationship Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>This field stores the status for a person</description>
    <inlineHelpText>This field stores the status for a person</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Master_Enterprise_Payload__e/Customer_Master_Enterprise_Payload__e.object-meta.xml
<CustomObject>
    <description>Customer Master Enterprise Payload</description>
    <label>Customer Master Enterprise Payload</label>
    <pluralLabel>Customer Master Enterprise Payload</pluralLabel>
</CustomObject>

force-app/main/default/objects/Customer_Master_Enterprise_Payload__e/fields/Input_Json__c.field-meta.xml
<CustomField>
    <fullName>Input_Json__c</fullName>
    <complianceGroup>PII</complianceGroup>
    <description>Input Json</description>
    <label>Input Json</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Customer_Master_Enterprise_Payload__e/fields/Process__c.field-meta.xml
<CustomField>
    <fullName>Process__c</fullName>
    <complianceGroup>HIPAA</complianceGroup>
    <description>Process</description>
    <label>Process</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CM_AccountContactRelationsTriggerHelper.cls
/***********************************************************************************************************************
* Name: CM_AccountContactRelationsTriggerHelper
* Copyright © Align Tech
* ========================================================================================================================
* Purpose: Helper class for CM_AccountContactRelationsTriggerHandler
* TestClass : CM_AccountContactRelationsTriggerHelper
* ========================================================================================================================
* History
*
* VERSION         AUTHOR                          DATE                DETAIL
* 1.0             Sruthi M                  08/01/2024          Trigger helper on the Account Contact Relationship
***********************************************************************************************************************/
public with sharing class CM_AccountContactRelationsTriggerHelper {
     
    /**    
    * @description : before event method of Account Contact relationship
    */
    public static void beforeEvent(List<AccountContactRelation> relationshipList) {  
        final Set<Id> accountIds = new Set<Id>();
        final Set<Id> contactIds = new Set<Id>();
        for(AccountContactRelation relation : relationshipList ) {
            if(relation.AccountContact_Id__c==null) {
                accountIds.add(relation.AccountId);  
                contactIds.add(relation.ContactId);    
            }    
        }
        if(accountIds!=null && !accountIds.isEmpty() && contactIds!=null && !contactIds.isEmpty()) {
            final Map<Id,Account> accountMap = new Map<Id,Account>([Select Id,MDM_Id__c from Account where Id = : accountIds WITH SECURITY_ENFORCED ]);
            final Map<Id,Contact> contactMap =  new Map<Id,Contact>([Select Id,MDM_Id__c from Contact where Id = : contactIds WITH SECURITY_ENFORCED ]);
            for(AccountContactRelation relation : relationshipList ) {
                if(relation.AccountContact_Id__c==null && accountMap!=null && contactMap!=null) {
                    relation.AccountContact_Id__c= accountMap.get(relation.AccountId).MDM_Id__c+ contactMap.get(relation.ContactId).MDM_Id__c;     
                }
            }
        }
    }   
    /**    
    * @description : before event method of Account Contact relationship
    */
    /*public static void afterUpdateEvent(List<AccountContactRelation> relationshipList,Map<Id,AccountContactRelation> oldRelationMap) {  
        final List < Customer_Master_Enterprise_Payload__e > payloadList = new List < Customer_Master_Enterprise_Payload__e > ();
        Customer_Master_Enterprise_Payload__e record;
        for (AccountContactRelation relationship: relationshipList) {
            if(relationship.Status__c != oldRelationMap.get(relationship.Id).Status__c && 
                relationship.Status__c=='Inactive' && relationship.IsDirect) {
                record = new Customer_Master_Enterprise_Payload__e();
                record.Input_Json__c = JSON.serialize(relationship);
                record.Process__c = CM_ReltioConstants.ACCCONRELALIONS;
                payloadList.add(record);
            }
        }
        if(payloadList!=null && !payloadList.isEmpty()) {
            eventbus.publish(payloadList);
        } 
    }*/
    private CM_AccountContactRelationsTriggerHelper() {} 
}