force-app/main/default/objects/Account/fields/MDM_Id__c.field-meta.xml
<CustomField>
    <fullName>MDM_Id__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>This is the MDM unique identifier</description>
    <externalId>true</externalId>
    <inlineHelpText>This is the MDM unique identifier</inlineHelpText>
    <label>MDM Id</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Timestamp__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>This field shall store the timestamp when the latest KAFKA request is received</description>
    <label>Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Organization_LOB_Information__c/Organization_LOB_Information__c.object-meta.xml
<CustomObject>
    <description>This object is used to capture detailed information about each line of business for an organization</description>
    <label>Organization LOB Information</label>
    <nameField>
        <displayFormat>OB-{000000}</displayFormat>
        <label>Organization LOB Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organization LOB Informations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Organization_LOB_Information__c/fields/MDM_Id__c.field-meta.xml
<CustomField>
    <fullName>MDM_Id__c</fullName>
    <businessOwnerGroup>CRM_Customer_Master_Owners</businessOwnerGroup>
    <complianceGroup>None</complianceGroup>
    <description>This is the MDM unique identifier</description>
    <externalId>true</externalId>
    <label>MDM Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Organization_LOB_Information__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <businessOwnerGroup>CRM_Customer_Master_Owners</businessOwnerGroup>
    <complianceGroup>None</complianceGroup>
    <description>This is Master-Details Relationship with the Organization Object</description>
    <label>Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Organization LOB Informations</relationshipLabel>
    <relationshipName>Organization_LOB_Informations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Organization_LOB_Information__c/fields/Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Timestamp__c</fullName>
    <businessOwnerGroup>CRM_Customer_Master_Owners</businessOwnerGroup>
    <complianceGroup>None</complianceGroup>
    <description>This field shall store the timestamp when the latest KAFKA request is received</description>
    <inlineHelpText>This field shall store the timestamp when the latest KAFKA request is received</inlineHelpText>
    <label>Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Organization_LOB_Information__c/fields/TimeStamp_Decimal__c.field-meta.xml
<CustomField>
    <fullName>TimeStamp_Decimal__c</fullName>
    <businessOwnerGroup>CRM_Customer_Master_Owners</businessOwnerGroup>
    <complianceGroup>None</complianceGroup>
    <description>Timestamp in decimal</description>
    <inlineHelpText>Timestamp in decimal</inlineHelpText>
    <label>TimeStamp Decimal</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CM_OrganizationLOB.cls
/***********************************************************************************************************************
 * Name: CM_OrganizationLOB
 * Copyright © Align Tech
 * ========================================================================================================================
 * Purpose: Service class for Organization LOB
 * TestClass : CM_OrganizationLOB
 * ========================================================================================================================
 * History
 *
 * VERSION         AUTHOR                          DATE                DETAIL
 * 1.0             Sonakshi Garg                   29/04/2024          Service class to retrieve Organization LOB data to upsert
 ***********************************************************************************************************************/
public with sharing class CM_OrganizationLOB {
    /**CM_ReltioHCOInboundPayloadTriggerHandler
     * @description : Method returns List of Organization LOB
     */
    public static Map < String, Organization_LOB_Information__c > upsertOrganizationLOB(Map < String, Map < String, Object >> objParser, Account account,String masterRecordId) {
     
        final Map < String, Organization_LOB_Information__c > orgLobMap = new Map < String, Organization_LOB_Information__c > ();
        Organization_LOB_Information__c orgLob ;
        Map < String, Object > key2value = new Map < String, Object > ();
        for (String objectKey: objParser.keySet()) {
            orgLob = new Organization_LOB_Information__c();
            orgLob.Organization__r = new Account(MDM_Id__c = account.MDM_Id__c);
            orgLob.Timestamp__c = account.Timestamp__c;
            orgLob.TimeStamp_Decimal__c = account.TimeStamp_Decimal__c;
            key2value = objParser.get(objectKey);
            for (String key: key2value.keyset()) {
                orgLob.put(key, key2value.get(key));
            }
            orgLobMap.put(objectKey, orgLob);
        }
     
        return orgLobMap;
    }
    private CM_OrganizationLOB() {}
}