force-app/main/default/objects/Account/fields/MDM_Id__c.field-meta.xml
<CustomField>
    <fullName>MDM_Id__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>This is the MDM unique identifier</description>
    <externalId>true</externalId>
    <inlineHelpText>This is the MDM unique identifier</inlineHelpText>
    <label>MDM Id</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Timestamp__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>This field shall store the timestamp when the latest KAFKA request is received</description>
    <label>Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Organization_Communication__c/Organization_Communication__c.object-meta.xml
<CustomObject>
    <label>Organization Communication</label>
    <nameField>
        <displayFormat>O-{000000}</displayFormat>
        <label>Organization Communication Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organization Communications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Organization_Communication__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>Master-details relationship to Account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Organization Communications</relationshipLabel>
    <relationshipName>Organization_Communications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Organization_Communication__c/fields/MDM_Id__c.field-meta.xml
<CustomField>
    <fullName>MDM_Id__c</fullName>
    <businessOwnerGroup>Customer_Master_Owners</businessOwnerGroup>
    <complianceGroup>None</complianceGroup>
    <description>Unique identifier</description>
    <externalId>true</externalId>
    <label>MDM Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Organization_Communication__c/fields/Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Timestamp__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>This field shall store the timestamp when the latest KAFKA request is received</description>
    <inlineHelpText>This field shall store the timestamp when the latest KAFKA request is received</inlineHelpText>
    <label>Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Organization_Communication__c/fields/TimeStamp_Decimal__c.field-meta.xml
<CustomField>
    <fullName>TimeStamp_Decimal__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>Timestamp in decimal</description>
    <inlineHelpText>Timestamp in decimal</inlineHelpText>
    <label>TimeStamp Decimal</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CM_CustomerInformationService.cls
/***********************************************************************************************************************
 * Name: CM_CustomerInformationService
 * Copyright © Align Tech
 * ========================================================================================================================
 * Purpose: Service class for Customer Communication Information
 * TestClass : CM_CustomerInformationService
 * ========================================================================================================================
 * History
 *
 * VERSION         AUTHOR                          DATE                DETAIL
 * 1.0             Rohit Jaiswal                   20/10/2023          Service class to retrieve Customer Communication data to upsert
 ***********************************************************************************************************************/
public with sharing class CM_CustomerInformationService {
    /**
     * @description : returns list of Customer communication information of Account
     */
    public static Map < String, Organization_Communication__c > upsertCommInformation(Map < String, Map < String, Object >> objParser, Account account,String masterRecordId) {
        CM_LoggerUtil.logger(new CM_Log('CustomerInformation','Info',String.valueof(Datetime.now()), masterRecordId, 'Customer Information Creation Service started'));  
        final Map < String, Organization_Communication__c > cusInformMap = new Map < String, Organization_Communication__c > ();
        Map < String, Object > key2values = new Map < String, Object > ();
        Organization_Communication__c cusInformation;
        for (String objectKey: objParser.keySet()) {
            cusInformation = new Organization_Communication__c();
            cusInformation.Account__r = new Account(MDM_Id__c = account.MDM_Id__c);
            cusInformation.Timestamp__c = account.Timestamp__c;
            cusInformation.TimeStamp_Decimal__c = account.TimeStamp_Decimal__c;
            key2values = objParser.get(objectKey);
            for (String key: key2values.keyset()) {
                cusInformation.put(key, key2values.get(key));
            }
            cusInformMap.put(objectKey, cusInformation);
        }
        CM_LoggerUtil.logger(new CM_Log('CustomerInformation','Info',String.valueof(Datetime.now()), masterRecordId, 'Customer Information Creation Service completed.'));  
        return cusInformMap;
    }
    private CM_CustomerInformationService() {}
}