force-app/main/default/objects/Account/fields/Operating_Units__c.field-meta.xml
<CustomField>
    <fullName>Operating_Units__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>Operating Unit</description>
    <label>Operating Units</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>4020_exocad_Gmbh</fullName>
            </value>
            <value>
                <fullName>4050_exocad_America</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Relationship__c/Account_Relationship__c.object-meta.xml
<CustomObject>
    <label>Organization Relationship</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Account Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organization Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Relationship__c/fields/From_Account__c.field-meta.xml
<CustomField>
    <fullName>From_Account__c</fullName>
    <businessOwnerGroup>Customer_Master_Owners</businessOwnerGroup>
    <complianceGroup>None</complianceGroup>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field stores parent Account details for HCO-HCO relationship</description>
    <inlineHelpText>This field stores parent Account details for HCO-HCO relationship</inlineHelpText>
    <label>From Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Relationships</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Relationship__c/fields/To_Account__c.field-meta.xml
<CustomField>
    <fullName>To_Account__c</fullName>
    <businessOwnerGroup>Customer_Master_Owners</businessOwnerGroup>
    <complianceGroup>None</complianceGroup>
    <description>This field stores child Account for HCO-HCO relationship</description>
    <inlineHelpText>This field stores child Account for HCO-HCO relationship</inlineHelpText>
    <label>To Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Relationships1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Customer_Master_Configurations__c/Customer_Master_Configurations__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Customer Master Configurations</description>
    <label>Customer Master Configurations</label>
</CustomObject>

force-app/main/default/classes/CM_AccountRelationshipTriggerHelperTest.cls
/**
* Name: CM_AccountRelationshipTriggerHelperTest
* Copyright © Align Tech
* Purpose : Test class for CM_AccountRelationshipTriggerHelperTest
* 
*/
/***********************************************************************************************************************
History

VERSION         AUTHOR                          DATE                DETAIL
1.0             Sruthi M                        11/03/2024          Test class for CM_AccountRelationshipTriggerHelper
***********************************************************************************************************************/
@isTest
private class CM_AccountRelationshipTriggerHelperTest {
	@testSetup static void setup() {
		Test.loadData(Customer_Master_Configurations__c.sObjectType, 'CustomerMasterConfigurations');
		UCB_TestDataFactory.createSObjectList('Account', new Map<String, Object>{ 'Name' => 'Test Acc', 'Operating_Units__c' => '4050_Exocad_America' }, 6);
	}
    @isTest 
    static void negativeTestResult() {
        final List<Account> accList= [Select Name,Operating_Units__c from Account Limit 10 ];

		Test.startTest();  

		UCB_TestDataFactory.createSObjectList('Account_Relationship__c', new Map<String, Object>{ 'From_Account__c' => new List<ID>{ accList[0].Id, accList[1].Id, accList[2].Id }, 'To_Account__c' => new List<ID>{ accList[4].Id, accList[5].Id, accList[3].Id } }, 3);

		Test.stopTest();

        final List<Account_Relationship__c> relatiosnhips= [Select Id from Account_Relationship__c Limit 10];
        System.assertEquals(relatiosnhips.size(),3,'Account relationship created');

	}
}