force-app/main/default/objects/Account/fields/Operating_Units__c.field-meta.xml
<CustomField>
    <fullName>Operating_Units__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>Operating Unit</description>
    <label>Operating Units</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>4020_exocad_Gmbh</fullName>
            </value>
            <value>
                <fullName>4050_exocad_America</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <complianceGroup>None</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related order</description>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CRM_Asset_Event__e/CRM_Asset_Event__e.object-meta.xml
<CustomObject>
    <description>Pubilshes platform event on asset create/update</description>
    <label>CRM Asset Event</label>
    <pluralLabel>CRM Asset Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/CRM_Asset_Event__e/fields/Asset_Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Asset_Event_Type__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>Describes Type of event Asset create/update</description>
    <label>Asset Event Type</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CRM_Asset_Event__e/fields/Asset_ID__c.field-meta.xml
<CustomField>
    <fullName>Asset_ID__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>Id of Asset which is created/updated</description>
    <label>Asset ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CRM_Asset_Event__e/fields/Order_ID__c.field-meta.xml
<CustomField>
    <fullName>Order_ID__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>Order related to Asset</description>
    <label>Order ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CRM_AssetEventSubcriberHandler_Test.cls
/***********************************************************************************************************************
* Name: CRM_AssetEventSubcriberHandler_Test
* Copyright © Align Tech
* ========================================================================================================================
* Purpose: Handles the triggered events on order
* TestClass : CRM_AssetEventSubcriberHandler_Test
* ========================================================================================================================
* History
*
* VERSION         AUTHOR                          DATE                DETAIL
* 1.0             Sruthi M                        18/03/2024          Test Class 
***********************************************************************************************************************/
@isTest
public class CRM_AssetEventSubcriberHandler_Test {
    
    /**
* @description: testdata set up 
*/     
    @TestSetup
    static void createTestData() {       
        final List<User> userLst1 = UCB_TestDataFactory.createSObjectList('User', new Map<String,Object> {
            'Username' => new List<String>{'test123456789@mycompany.dv01','test123456789@mycompany.dv02','test123456789@mycompany.dv03'},'ProfileId' => new List<Id>{UserInfo.getProfileId(),UserInfo.getProfileId(),UserInfo.getProfileId()},
                'CommunityNickname' => new List<String>{'testUser01','testUser02','testUser03'}},3);
        
        System.RunAs(new user(ID = UserInfo.getUserID())) { 
            final List<User> userLst2 = [select id,Username from user where Username like '%test123456789@mycompany%'];            
            
            final List<Account> accLst = UCB_TestDataFactory.createSObjectList('Account',new Map<String,Object>{
                'Name' => 'Test Acc', 'Operating_Units__c' => '4050_Exocad_America','OwnerId'=>userLst2[0].Id},5);   
            
            final List<Order> ordLst = UCB_TestDataFactory.createSObjectList('Order', new Map<String,Object> {
                'AccountId' =>accLst[0].Id,'OwnerId' => userLst2[0].Id,
                    'EffectiveDate'=>Date.newInstance(2024,03,12),
                    'Status'=> 'Draft'},3);                                               
        }                    
    }    
    
    /*
* @description : Asset trigger handler for after insert
*/
    @isTest
    static void testAssetEventSubscriber() {         
        try{
            
            final List<Account> accLst = [select id,Name,ownerID from Account where name like '%Test%'];
            final List<Order> ordLst = [select id,ownerID from Order where Status= 'Draft'];
            final List<User> userLst2 = [select id,Username from user where Username like '%test123456789@mycompany%'];
            
            final List<Asset> asstLst = UCB_TestDataFactory.createSObjectList('Asset', new Map<String,Object> {
                'Name' => 'Test Asset',
                    'AccountId' => accLst[0].Id,           
                    'Order__c'=> ordLst[0].Id,'Status'=> 'Draft'},3);             
            
            final List<CRM_Asset_Event__e> asstEvntLst = UCB_TestDataFactory.createSObjectList('CRM_Asset_Event__e',new Map<String,Object> {
                'Order_ID__c' => ordLst[0].Id,'Asset_ID__c'=>asstLst[0].Id,'Asset_Event_Type__c'=>'Create_Asset'},5,false); 
            system.debug('asstEvntLst==>>'+asstEvntLst);
            
            Test.startTest();
            Database.SaveResult[] sr = EventBus.publish(asstEvntLst);
            Test.stopTest();
            system.debug('save result==>>'+sr);
            for(Database.SaveResult res : sr){
                system.debug('result==>>'+res);
                System.assertEquals(true, res.isSuccess());
            }
            
            ID ordOwnerID = [select id,AccountId,Account.ownerID,ownerId from order Limit 1].ownerID;
            Id accOwnerID = [select id,ownerid from Account limit 1].ownerId;
            system.debug('ordOwnerID==>>'+ordOwnerID);
            system.debug('accOwnerID==>>'+accOwnerID);
            
            
        } Catch(Exception excp) {
            system.debug('Exception==>>'+excp.getMessage());
            system.debug('Exception==>>'+excp.getStackTraceString());    
        }
    }
 
    /*
* @description : Asset trigger handler for after insert
*/
    @isTest
    static void testAssetEventSubscriber2() {         
        try{
            
            final List<Account> accLst = [select id,Name,ownerID from Account where name like '%Test%'];
            final List<Order> ordLst = [select id,ownerID from Order where Status= 'Draft'];
            final List<User> userLst2 = [select id,Username from user where Username like '%test123456789@mycompany%'];
            
            final List<Asset> asstLst = UCB_TestDataFactory.createSObjectList('Asset', new Map<String,Object> {
                'Name' => 'Test Asset',
                    'AccountId' => accLst[0].Id,'ownerId' => userLst2[2].Id,         
                    'Order__c'=> ordLst[0].Id,'Status'=> 'Draft'},3);             
            system.debug('asstLst==>>'+asstLst);
            final List<CRM_Asset_Event__e> asstEvntLst = UCB_TestDataFactory.createSObjectList('CRM_Asset_Event__e',new Map<String,Object> {},5,false); 
            system.debug('asstEvntLst==>>'+asstEvntLst);
            
            Test.startTest();
            Database.SaveResult[] sveRslt = EventBus.publish(asstEvntLst);            
            Test.stopTest();
            //system.debug('save result==>>'+sveRslt);
            for(Database.SaveResult res : sveRslt){
                system.debug('result==>>'+res);
                System.assertEquals(false, res.isSuccess());
            }
            
            ID ordOwnerID = [select id,AccountId,Account.ownerID,ownerId from order Limit 1].ownerID;
            Id accOwnerID = [select id,ownerid from Account limit 1].ownerId;
            system.debug('ordOwnerID==>>'+ordOwnerID);
            system.debug('accOwnerID==>>'+accOwnerID);
            
            
        } Catch(Exception excp) {
            system.debug('Exception==>>'+excp.getMessage());
            system.debug('Exception==>>'+excp.getStackTraceString());    
        }
    }
    
    /*
* @description : Asset trigger handler for after insert
*/
    @isTest
    static void testAssetEventSubscriber3() {         
        try{
            
            final List<Account> accLst = [select id,Name,ownerID from Account where name like '%Test%'];
            final List<Order> ordLst = [select id,ownerID from Order where Status= 'Draft'];
            final List<User> userLst2 = [select id,Username from user where Username like '%test123456789@mycompany%'];
            
            final List<Asset> asstLst = UCB_TestDataFactory.createSObjectList('Asset', new Map<String,Object> {
                'Name' => 'Test Asset',
                    'AccountId' => accLst[0].Id,'ownerId' => userLst2[2].Id,         
                    'Order__c'=> ordLst[0].Id,'Status'=> 'Draft'},3);             
            system.debug('asstLst==>>'+asstLst);
            final List<CRM_Asset_Event__e> asstEvntLst = UCB_TestDataFactory.createSObjectList('CRM_Asset_Event__e',new Map<String,Object> {},5,false); 
            system.debug('asstEvntLst==>>'+asstEvntLst);
            
             FailureAndSuccessCallback cb = new FailureAndSuccessCallback();
            //Test.startTest();
            Database.SaveResult[] sveRslt = EventBus.publish(asstEvntLst,cb);   
            
           
            //Test.stopTest();
             // Fail event 
            // (invoke onFailure and DO NOT deliver event to subscribers)
            Test.getEventBus().fail(); 
            //system.debug('save result==>>'+sveRslt);
            /*for(Database.SaveResult res : sveRslt){
                system.debug('result==>>'+res);
                System.assertEquals(false, res.isSuccess());
            }
            */
            ID ordOwnerID = [select id,AccountId,Account.ownerID,ownerId from order Limit 1].ownerID;
            Id accOwnerID = [select id,ownerid from Account limit 1].ownerId;
            system.debug('ordOwnerID==>>'+ordOwnerID);
            system.debug('accOwnerID==>>'+accOwnerID);
            
            
        } Catch(Exception excp) {
            system.debug('Exception==>>'+excp.getMessage());
            system.debug('Exception==>>'+excp.getStackTraceString());    
        }
    }    
}