force-app/main/default/objects/Contact/fields/Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Timestamp__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>This is used to store the latest KAFKA request JSON updated time</description>
    <label>Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Person_Communication__c/Person_Communication__c.object-meta.xml
<CustomObject>
    <label>Person Communication</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Person Communication Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Person Communications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Person_Communication__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>Master-details relationship to Contact</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Person Communications</relationshipLabel>
    <relationshipName>Person_Communications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Person_Communication__c/fields/MDM_Id__c.field-meta.xml
<CustomField>
    <fullName>MDM_Id__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>Unique identifier</description>
    <externalId>true</externalId>
    <label>MDM Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person_Communication__c/fields/TimeStamp_Decimal__c.field-meta.xml
<CustomField>
    <fullName>TimeStamp_Decimal__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>Timestamp in decimal</description>
    <inlineHelpText>Timestamp in decimal</inlineHelpText>
    <label>TimeStamp Decimal</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CM_PersonCommunicationService.cls
/***********************************************************************************************************************
 * Name: CM_PersonCommunicationService
 * Copyright © Align Tech
 * ========================================================================================================================
 * Purpose: Service class to handle HCP Communication Details
 * TestClass : CM_PersonCommunicationService
 * ========================================================================================================================
 * History
 *
 * VERSION         AUTHOR                          DATE                DETAIL
 * 1.0             Sruthi M                   28/11/2023          Service class to retrieve HCP Communication Details to upsert
 ***********************************************************************************************************************/
public with sharing class CM_PersonCommunicationService {
    /**
     * @description : Method to get List of HCP Communication details.
     */
    public static Map < String, Person_Communication__c > upsertHCPcommunicationInfo(Map < String, Map < String, Object >> objParser, Contact reltdContact,String masterRecordId) {
        CM_LoggerUtil.logger(new CM_Log('PersonCommunication','Info',String.valueof(Datetime.now()), masterRecordId, 'Person Communication Creation Service Started'));
        final Map < String, Person_Communication__c > communicationMap = new Map < String, Person_Communication__c > ();
        Person_Communication__c communicationInfo;

        Map < String, Object > key2value = new Map < String, Object > ();
        for (String objectKey: objParser.keySet()) {
            communicationInfo = new Person_Communication__c();
            communicationInfo.Contact__r = new Contact(MDM_Id__c = reltdContact.MDM_Id__c);
            communicationInfo.Timestamp__c = reltdContact.Timestamp__c;
            communicationInfo.TimeStamp_Decimal__c = reltdContact.TimeStamp_Decimal__c;
            key2value = objParser.get(objectKey);
            for (String key: key2value.keyset()) {
                communicationInfo.put(key, key2value.get(key));
            }
            communicationMap.put(objectKey, communicationInfo);
        }
        CM_LoggerUtil.logger(new CM_Log('PersonCommunication','Info',String.valueof(Datetime.now()), masterRecordId, 'Person Communication Creation Service Completed'));
        return communicationMap;
    }
    private CM_PersonCommunicationService() {}
}