force-app/main/default/objects/Contact/fields/Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Timestamp__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>This is used to store the latest KAFKA request JSON updated time</description>
    <label>Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Educational_Detail__c/Educational_Detail__c.object-meta.xml
<CustomObject>
    <description>Education details of HCP</description>
    <label>Educational Detail</label>
    <nameField>
        <displayFormat>E-{000000}</displayFormat>
        <label>Educational Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Educational Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Educational_Detail__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>Lookup to contact</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Educational Details</relationshipLabel>
    <relationshipName>Educational_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Educational_Detail__c/fields/MDM_Id__c.field-meta.xml
<CustomField>
    <fullName>MDM_Id__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>Education details</description>
    <externalId>true</externalId>
    <label>MDM Id</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Educational_Detail__c/fields/TimeStamp_Decimal__c.field-meta.xml
<CustomField>
    <fullName>TimeStamp_Decimal__c</fullName>
    <description>Timestamp in decimal</description>
    <inlineHelpText>Timestamp in decimal</inlineHelpText>
    <label>TimeStamp Decimal</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CM_EducationalDetailsService.cls
/***********************************************************************************************************************
 * Name: CM_EducationalDetailsService
 * Copyright © Align Tech
 * ========================================================================================================================
 * Purpose: Service class to handle HCP Education Details
 * TestClass : CM_EducationalDetailsService
 * ========================================================================================================================
 * History
 *
 * VERSION         AUTHOR                          DATE                DETAIL
 * 1.0             Sruthi M                   13/11/2023           Service class to retrieve HCP Education data to upsert
 ***********************************************************************************************************************/
public with sharing class CM_EducationalDetailsService {
    /**
     * @description : Method returns data about HCP Education 
     */
    public static Map < String, Educational_Detail__c > upsertEducationalDetails(Map < String, Map < String, Object >> objParser, Contact reltdContact,String masterRecordId) {
        CM_LoggerUtil.logger(new CM_Log(String.valueof(Datetime.now()), masterRecordId, 'Education Details Creation Service Started'));
        final Map < String, Educational_Detail__c > hcpEduMap = new Map < String, Educational_Detail__c > ();
        Educational_Detail__c hcpEduDetails;

        Map < String, Object > key2value = new Map < String, Object > ();
        for (String objectKey: objParser.keySet()) {
            hcpEduDetails = new Educational_Detail__c();
            hcpEduDetails.Contact__r = new Contact(MDM_Id__c = reltdContact.MDM_Id__c);
            hcpEduDetails.Timestamp__c = reltdContact.Timestamp__c;
            hcpEduDetails.TimeStamp_Decimal__c = reltdContact.TimeStamp_Decimal__c;
            key2value = objParser.get(objectKey);
            for (String key: key2value.keyset()) {
                hcpEduDetails.put(key, key2value.get(key));
            }
            hcpEduMap.put(objectKey, hcpEduDetails);
        }
        CM_LoggerUtil.logger(new CM_Log(String.valueof(Datetime.now()), masterRecordId, 'Education Details Creation Service Started'));
        return hcpEduMap;
    }
    private CM_EducationalDetailsService() {}
}