force-app/main/default/objects/Contact/fields/Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Timestamp__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>This is used to store the latest KAFKA request JSON updated time</description>
    <label>Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/License_Information__c/License_Information__c.object-meta.xml
<CustomObject>
    <label>License Information</label>
    <nameField>
        <displayFormat>L-{000000}</displayFormat>
        <label>License Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>License Informations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/License_Information__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>Lookup to Contact</description>
    <inlineHelpText>Lookup to Contact</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>License Informations</relationshipLabel>
    <relationshipName>License_Informations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/License_Information__c/fields/MDM_Id__c.field-meta.xml
<CustomField>
    <fullName>MDM_Id__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>License Information of HCP</description>
    <externalId>true</externalId>
    <label>MDM Id</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Information__c/fields/Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Timestamp__c</fullName>
    <complianceGroup>None</complianceGroup>
    <description>This field shall store the timestamp when the latest KAFKA request is received</description>
    <inlineHelpText>This field shall store the timestamp when the latest KAFKA request is received</inlineHelpText>
    <label>Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/CM_LicenseInformationService.cls
/***********************************************************************************************************************
 * Name: CM_LicenseInformationService
 * Copyright © Align Tech
 * ========================================================================================================================
 * Purpose: Service class to handle HCP License Information
 * TestClass : CM_LicenseInformationService
 * ========================================================================================================================
 * History
 *
 * VERSION         AUTHOR                          DATE                DETAIL
 * 1.0             Sruthi M                   17/11/2023           Service class to retrieve HCP License Information data to upsert
 ***********************************************************************************************************************/
public with sharing class CM_LicenseInformationService {
    /**
     * @description : Method to get List of HCP License Information
     */
    public static Map < String, License_Information__c > upsertLicenseInformationDetails(Map < String, Map < String, Object >> objParser, Contact reltdContact) {
        //UCB_LoggerService.logger(new List<UCB_Log>{new UCB_Log(RELTIOHCP,'License Information Creation Service','License Information Creation Service Started')});
        final Map < String, License_Information__c > hcpLicenseMap = new Map < String, License_Information__c > ();
        License_Information__c hcpLicenseInfo;

        Map < String, Object > key2value = new Map < String, Object > ();
        for (String objectKey: objParser.keySet()) {
            hcpLicenseInfo = new License_Information__c();
            hcpLicenseInfo.Contact__r = new Contact(MDM_ID__c = reltdContact.MDM_Id__c);
            hcpLicenseInfo.Timestamp__c = reltdContact.Timestamp__c;
            hcpLicenseInfo.TimeStamp_Decimal__c = reltdContact.TimeStamp_Decimal__c;
            key2value = objParser.get(objectKey);
            for (String key: key2value.keyset()) {
                hcpLicenseInfo.put(key, key2value.get(key));
            }
            hcpLicenseMap.put(objectKey, hcpLicenseInfo);
        }
        //UCB_LoggerService.logger(new List<UCB_Log>{new UCB_Log(RELTIOHCP,'License Information Creation Service','License Information Creation Service ended')});
        return hcpLicenseMap;
    }
    private CM_LicenseInformationService() {}
}